/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial14.c                                             *
* Font:        Arial                                                 *
* Height:      14                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  14                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial14;

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0020[ 14] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0021[ 14] = { /* code 0021 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0022[ 14] = { /* code 0022 */
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0023[ 14] = { /* code 0023 */
  ________,
  ________,
  ________,
  __X_X___,
  __X_X___,
  XXXXX___,
  _X_X____,
  _X_X____,
  XXXXX___,
  X_X_____,
  X_X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0024[ 14] = { /* code 0024 */
  ________,
  ________,
  ________,
  _XXX____,
  X_X_X___,
  X_X_____,
  _XXX____,
  __X_X___,
  __X_X___,
  X_X_X___,
  _XXX____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0025[ 28] = { /* code 0025 */
  ________,________,
  ________,________,
  ________,________,
  _XX___X_,________,
  X__X_X__,________,
  X__X_X__,________,
  _XX_X___,________,
  ____X_XX,________,
  ___X_X__,X_______,
  ___X_X__,X_______,
  __X___XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0026[ 14] = { /* code 0026 */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  __XX____,
  _X_X____,
  X___XX__,
  X___X___,
  _XXX_X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0027[ 14] = { /* code 0027 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0028[ 14] = { /* code 0028 */
  ________,
  ________,
  ________,
  __X_____,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0029[ 14] = { /* code 0029 */
  ________,
  ________,
  ________,
  X_______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002A[ 14] = { /* code 002A */
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  _X______,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002B[ 14] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002C[ 14] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002D[ 14] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002E[ 14] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_002F[ 14] = { /* code 002F */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0030[ 14] = { /* code 0030 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0031[ 14] = { /* code 0031 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0032[ 14] = { /* code 0032 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0033[ 14] = { /* code 0033 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  __XX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0034[ 14] = { /* code 0034 */
  ________,
  ________,
  ________,
  ___X____,
  __XX____,
  _X_X____,
  _X_X____,
  X__X____,
  XXXXX___,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0035[ 14] = { /* code 0035 */
  ________,
  ________,
  ________,
  _XXXX___,
  _X______,
  X_______,
  XXXX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0036[ 14] = { /* code 0036 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0037[ 14] = { /* code 0037 */
  ________,
  ________,
  ________,
  XXXXX___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0038[ 14] = { /* code 0038 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0039[ 14] = { /* code 0039 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003A[ 14] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003B[ 14] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003C[ 14] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ____X___,
  _XXX____,
  X_______,
  _XXX____,
  ____X___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003D[ 14] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ________,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003E[ 14] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  _XXX____,
  ____X___,
  _XXX____,
  X_______,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_003F[ 14] = { /* code 003F */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  ________,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0040[ 28] = { /* code 0040 */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  _XX_____,X_______,
  _X__XX_X,_X______,
  X__X__XX,_X______,
  X_X___X_,_X______,
  X_X___X_,_X______,
  X_X__XX_,X_______,
  X__XX_XX,________,
  _X______,_X______,
  __XXXXXX,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0041[ 14] = { /* code 0041 */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  __X_X___,
  __X_X___,
  _X___X__,
  _XXXXX__,
  X_____X_,
  X_____X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0042[ 14] = { /* code 0042 */
  ________,
  ________,
  ________,
  XXXXX___,
  X____X__,
  X____X__,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0043[ 14] = { /* code 0043 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0044[ 14] = { /* code 0044 */
  ________,
  ________,
  ________,
  XXXX____,
  X___X___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___X___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0045[ 14] = { /* code 0045 */
  ________,
  ________,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0046[ 14] = { /* code 0046 */
  ________,
  ________,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0047[ 14] = { /* code 0047 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_______,
  X___XXX_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0048[ 14] = { /* code 0048 */
  ________,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0049[ 14] = { /* code 0049 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004A[ 14] = { /* code 004A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004B[ 14] = { /* code 004B */
  ________,
  ________,
  ________,
  X____X__,
  X___X___,
  X__X____,
  X_XX____,
  XX_X____,
  X___X___,
  X___X___,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004C[ 14] = { /* code 004C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004D[ 14] = { /* code 004D */
  ________,
  ________,
  ________,
  X_____X_,
  XX___XX_,
  XX___XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X__X__X_,
  X__X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004E[ 14] = { /* code 004E */
  ________,
  ________,
  ________,
  X____X__,
  XX___X__,
  X_X__X__,
  X_X__X__,
  X__X_X__,
  X__X_X__,
  X___XX__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_004F[ 14] = { /* code 004F */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0050[ 14] = { /* code 0050 */
  ________,
  ________,
  ________,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0051[ 14] = { /* code 0051 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X__XX_X_,
  _X___X__,
  __XXX_X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0052[ 14] = { /* code 0052 */
  ________,
  ________,
  ________,
  XXXXX___,
  X____X__,
  X____X__,
  XXXXX___,
  X__X____,
  X___X___,
  X___X___,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0053[ 14] = { /* code 0053 */
  ________,
  ________,
  ________,
  _XXXX___,
  X____X__,
  X_______,
  _XX_____,
  ___XX___,
  _____X__,
  X____X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0054[ 14] = { /* code 0054 */
  ________,
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0055[ 14] = { /* code 0055 */
  ________,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0056[ 14] = { /* code 0056 */
  ________,
  ________,
  ________,
  X_____X_,
  X_____X_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0057[ 28] = { /* code 0057 */
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X______,
  ___X_X__,_X______,
  X__X_X__,X_______,
  X__X_X__,X_______,
  X_X___X_,X_______,
  X_X___X_,X_______,
  _X_____X,________,
  _X_____X,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0058[ 14] = { /* code 0058 */
  ________,
  ________,
  ________,
  X____X__,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  _X__X___,
  _X__X___,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0059[ 14] = { /* code 0059 */
  ________,
  ________,
  ________,
  X_____X_,
  _X___X__,
  _X___X__,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005A[ 14] = { /* code 005A */
  ________,
  ________,
  ________,
  _XXXXX__,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005B[ 14] = { /* code 005B */
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005C[ 14] = { /* code 005C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005D[ 14] = { /* code 005D */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005E[ 14] = { /* code 005E */
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  X___X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_005F[ 14] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0060[ 14] = { /* code 0060 */
  ________,
  ________,
  ________,
  X_______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0061[ 14] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0062[ 14] = { /* code 0062 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  XX__X___,
  X_XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0063[ 14] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X_______,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0064[ 14] = { /* code 0064 */
  ________,
  ________,
  ________,
  ____X___,
  ____X___,
  _XX_X___,
  X__XX___,
  X___X___,
  X___X___,
  X__XX___,
  _XX_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0065[ 14] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0066[ 14] = { /* code 0066 */
  ________,
  ________,
  ________,
  __X_____,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0067[ 14] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_X___,
  X__XX___,
  X___X___,
  X___X___,
  X__XX___,
  _XX_X___,
  ____X___,
  XXXX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0068[ 14] = { /* code 0068 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0069[ 14] = { /* code 0069 */
  ________,
  ________,
  ________,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006A[ 14] = { /* code 006A */
  ________,
  ________,
  ________,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006B[ 14] = { /* code 006B */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X__X____,
  X_X_____,
  XX______,
  X_X_____,
  X_X_____,
  X__X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006C[ 14] = { /* code 006C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006D[ 14] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_XXXX__,
  XX_X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006E[ 14] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_006F[ 14] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0070[ 14] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  XX__X___,
  X_XX____,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0071[ 14] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_X___,
  X__XX___,
  X___X___,
  X___X___,
  X__XX___,
  _XX_X___,
  ____X___,
  ____X___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0072[ 14] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0073[ 14] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  _XX_____,
  ___X____,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0074[ 14] = { /* code 0074 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0075[ 14] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X__XX___,
  _XX_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0076[ 14] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0077[ 28] = { /* code 0077 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  X___X___,X_______,
  X__X_X__,X_______,
  _X_X_X_X,________,
  _X_X_X_X,________,
  __X___X_,________,
  __X___X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0078[ 14] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  _X_X____,
  __X_____,
  __X_____,
  _X_X____,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_0079[ 14] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007A[ 14] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007B[ 14] = { /* code 007B */
  ________,
  ________,
  ________,
  __X_____,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007C[ 14] = { /* code 007C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007D[ 14] = { /* code 007D */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007E[ 14] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_X___,
  X_XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_007F[ 14] = { /* code 007F */
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A0[ 14] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A1[ 14] = { /* code 00A1 */
  __X_X___,
  __XXX___,
  ________,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A2[ 14] = { /* code 00A2 */
  ________,
  ________,
  _X_X____,
  _XXX____,
  ________,
  X___X___,
  X___X___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A3[ 14] = { /* code 00A3 */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A4[ 14] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  X____X__,
  _XXXX___,
  _X__X___,
  _X__X___,
  _XXXX___,
  X____X__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A5[ 14] = { /* code 00A5 */
  ________,
  ____X___,
  ____X___,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A6[ 14] = { /* code 00A6 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A7[ 14] = { /* code 00A7 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  _X______,
  XXX_____,
  X__X____,
  _X__X___,
  __X_X___,
  ___X____,
  X___X___,
  _XXX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A8[ 14] = { /* code 00A8 */
  ________,
  __X_X___,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00A9[ 14] = { /* code 00A9 */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X__XXX_X,
  X_X____X,
  X_X__X_X,
  X__XX__X,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AA[ 14] = { /* code 00AA */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_______,
  XXXX____,
  X_______,
  X_______,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AB[ 14] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  _X_X____,
  X_X_____,
  _X_X____,
  __X_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AC[ 14] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ____X___,
  ____X___,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AD[ 14] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AE[ 14] = { /* code 00AE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X_XXX__X,
  X_X__X_X,
  X_XXX__X,
  X_X__X_X,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00AF[ 14] = { /* code 00AF */
  ________,
  _X______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B0[ 14] = { /* code 00B0 */
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B1[ 14] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  ________,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B2[ 14] = { /* code 00B2 */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B3[ 14] = { /* code 00B3 */
  ________,
  ________,
  ________,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B4[ 14] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B5[ 14] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XXXXX___,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B6[ 14] = { /* code 00B6 */
  ________,
  ________,
  ________,
  _XXXXX__,
  XXX_X___,
  XXX_X___,
  _XX_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B7[ 14] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B8[ 14] = { /* code 00B8 */
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00B9[ 28] = { /* code 00B9 */
  ________,________,
  ________,________,
  ________,________,
  _X____X_,________,
  _XX___X_,_XX_____,
  _XX___X_,X__X____,
  _X_X__X_,X__X____,
  _X__X_X_,_XX_____,
  _X___XX_,________,
  _X___XX_,XXXX____,
  _X____X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BA[ 14] = { /* code 00BA */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  XXX_____,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BB[ 14] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  _X_X____,
  __X_X___,
  _X_X____,
  X_X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BC[ 14] = { /* code 00BC */
  ________,
  ________,
  ________,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BD[ 14] = { /* code 00BD */
  ________,
  ________,
  ________,
  _XXXX___,
  X____X__,
  X_______,
  _XX_____,
  ___XX___,
  _____X__,
  X____X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BE[ 14] = { /* code 00BE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  _XX_____,
  ___X____,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00BF[ 14] = { /* code 00BF */
  ________,
  ________,
  ________,
  _X______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C0[ 14] = { /* code 00C0 */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  __X_X___,
  __X_X___,
  _X___X__,
  _XXXXX__,
  X_____X_,
  X_____X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C1[ 14] = { /* code 00C1 */
  ________,
  ________,
  ________,
  _XXXX___,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C2[ 14] = { /* code 00C2 */
  ________,
  ________,
  ________,
  XXXXX___,
  X____X__,
  X____X__,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C3[ 14] = { /* code 00C3 */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C4[ 14] = { /* code 00C4 */
  ________,
  ________,
  ________,
  __XXXX__,
  __X__X__,
  __X__X__,
  __X__X__,
  __X__X__,
  __X__X__,
  _X___X__,
  XXXXXXX_,
  X_____X_,
  X_____X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C5[ 14] = { /* code 00C5 */
  ________,
  ________,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C6[ 28] = { /* code 00C6 */
  ________,________,
  ________,________,
  ________,________,
  XX___X__,_XX_____,
  __X__X__,X_______,
  __X__X__,X_______,
  ___XXXXX,________,
  __X__X__,X_______,
  __X__X__,X_______,
  _X___X__,_X______,
  X____X__,__X_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C7[ 14] = { /* code 00C7 */
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  __XX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C8[ 28] = { /* code 00C8 */
  ________,________,
  ________,________,
  ________,________,
  _X____X_,________,
  _X___XX_,________,
  _X__X_X_,________,
  _X__X_X_,________,
  _X_X__X_,________,
  _X_X__X_,________,
  _XX___X_,________,
  _X____X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00C9[ 28] = { /* code 00C9 */
  ___X_X__,________,
  ___XXX__,________,
  ________,________,
  _X____X_,________,
  _X___XX_,________,
  _X__X_X_,________,
  _X__X_X_,________,
  _X_X__X_,________,
  _X_X__X_,________,
  _XX___X_,________,
  _X____X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CA[ 14] = { /* code 00CA */
  ________,
  ________,
  ________,
  _X___X__,
  _X__X___,
  _X_X____,
  _XX_____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CB[ 14] = { /* code 00CB */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CC[ 14] = { /* code 00CC */
  ________,
  ________,
  ________,
  X_____X_,
  XX___XX_,
  XX___XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X__X__X_,
  X__X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CD[ 14] = { /* code 00CD */
  ________,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CE[ 14] = { /* code 00CE */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00CF[ 14] = { /* code 00CF */
  ________,
  ________,
  ________,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D0[ 14] = { /* code 00D0 */
  ________,
  ________,
  ________,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D1[ 14] = { /* code 00D1 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D2[ 14] = { /* code 00D2 */
  ________,
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D3[ 14] = { /* code 00D3 */
  ________,
  ________,
  ________,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D4[ 14] = { /* code 00D4 */
  ________,
  ________,
  ________,
  ___X____,
  _XXXXX__,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  _XXXXX__,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D5[ 14] = { /* code 00D5 */
  ________,
  ________,
  ________,
  X____X__,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  _X__X___,
  _X__X___,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D6[ 14] = { /* code 00D6 */
  ________,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  XXXXXXX_,
  ______X_,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D7[ 14] = { /* code 00D7 */
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D8[ 28] = { /* code 00D8 */
  ________,________,
  ________,________,
  ________,________,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00D9[ 28] = { /* code 00D9 */
  ________,________,
  ________,________,
  ________,________,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,XX______,
  ________,_X______,
  ________,_X______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DA[ 14] = { /* code 00DA */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __XXXX__,
  __X___X_,
  __X___X_,
  __X___X_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DB[ 28] = { /* code 00DB */
  ________,________,
  ________,________,
  ________,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _XXXX__X,________,
  _X___X_X,________,
  _X___X_X,________,
  _X___X_X,________,
  _XXXX__X,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DC[ 14] = { /* code 00DC */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DD[ 14] = { /* code 00DD */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ______X_,
  ___XXXX_,
  ______X_,
  ______X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DE[ 28] = { /* code 00DE */
  ________,________,
  ________,________,
  ________,________,
  _X___XXX,________,
  _X__X___,X_______,
  _X_X____,_X______,
  _X_X____,_X______,
  _XXX____,_X______,
  _X_X____,_X______,
  _X__X___,X_______,
  _X___XXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00DF[ 14] = { /* code 00DF */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  __XXXXX_,
  ___X__X_,
  __X___X_,
  _X____X_,
  _X____X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E0[ 14] = { /* code 00E0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E1[ 14] = { /* code 00E1 */
  ________,
  ________,
  ________,
  _XXXX___,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E2[ 14] = { /* code 00E2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X__X___,
  _XXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E3[ 14] = { /* code 00E3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E4[ 14] = { /* code 00E4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  X__X____,
  XXXXX___,
  X___X___,
  X___X___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E5[ 14] = { /* code 00E5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E6[ 14] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X__X_,
  _X_X_X__,
  __XXX___,
  _X_X_X__,
  _X_X_X__,
  X__X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E7[ 14] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  __X_____,
  ___X____,
  X__X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E8[ 14] = { /* code 00E8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X__XX___,
  X_X_X___,
  X_X_X___,
  XX__X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00E9[ 14] = { /* code 00E9 */
  ________,
  ________,
  _X_X____,
  _XXX____,
  ________,
  X___X___,
  X__XX___,
  X_X_X___,
  X_X_X___,
  XX__X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00EA[ 14] = { /* code 00EA */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X_X_____,
  XX______,
  X_X_____,
  X_X_____,
  X__X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00EB[ 14] = { /* code 00EB */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00EC[ 14] = { /* code 00EC */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X__X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00ED[ 14] = { /* code 00ED */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  XXXXX___,
  X___X___,
  X___X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00EE[ 14] = { /* code 00EE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00EF[ 14] = { /* code 00EF */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F0[ 14] = { /* code 00F0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  XX__X___,
  X_XX____,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F1[ 14] = { /* code 00F1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X_______,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F2[ 14] = { /* code 00F2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F3[ 14] = { /* code 00F3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F4[ 14] = { /* code 00F4 */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  _XXXXX__,
  ___X____,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F5[ 14] = { /* code 00F5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  _X_X____,
  __X_____,
  __X_____,
  _X_X____,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F6[ 14] = { /* code 00F6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XXXXXX__,
  _____X__,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F7[ 14] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  ____X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F8[ 14] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00F9[ 14] = { /* code 00F9 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _XXXXXXX,
  _______X,
  _______X,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FA[ 14] = { /* code 00FA */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  __XXX___,
  __X__X__,
  __X__X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FB[ 14] = { /* code 00FB */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_____X_,
  X_____X_,
  XXXX__X_,
  X___X_X_,
  X___X_X_,
  XXXX__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FC[ 14] = { /* code 00FC */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FD[ 14] = { /* code 00FD */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  __XXX___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FE[ 14] = { /* code 00FE */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__XXX__,
  X_X___X_,
  XXX___X_,
  X_X___X_,
  X_X___X_,
  X__XXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial14_00FF[ 14] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X__X___,
  _X__X___,
  __XXX___,
  _X__X___,
  _X__X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontArial14_CharInfo[192] = {
   {   3,   3,  1, acGUI_FontArial14_0020 } /* code 0020 */
  ,{   2,   2,  1, acGUI_FontArial14_0021 } /* code 0021 */
  ,{   4,   4,  1, acGUI_FontArial14_0022 } /* code 0022 */
  ,{   6,   6,  1, acGUI_FontArial14_0023 } /* code 0023 */
  ,{   6,   6,  1, acGUI_FontArial14_0024 } /* code 0024 */
  ,{  10,  10,  2, acGUI_FontArial14_0025 } /* code 0025 */
  ,{   7,   7,  1, acGUI_FontArial14_0026 } /* code 0026 */
  ,{   2,   2,  1, acGUI_FontArial14_0027 } /* code 0027 */
  ,{   4,   4,  1, acGUI_FontArial14_0028 } /* code 0028 */
  ,{   4,   4,  1, acGUI_FontArial14_0029 } /* code 0029 */
  ,{   4,   4,  1, acGUI_FontArial14_002A } /* code 002A */
  ,{   6,   6,  1, acGUI_FontArial14_002B } /* code 002B */
  ,{   3,   3,  1, acGUI_FontArial14_002C } /* code 002C */
  ,{   4,   4,  1, acGUI_FontArial14_002D } /* code 002D */
  ,{   3,   3,  1, acGUI_FontArial14_002E } /* code 002E */
  ,{   3,   3,  1, acGUI_FontArial14_002F } /* code 002F */
  ,{   6,   6,  1, acGUI_FontArial14_0030 } /* code 0030 */
  ,{   6,   6,  1, acGUI_FontArial14_0031 } /* code 0031 */
  ,{   6,   6,  1, acGUI_FontArial14_0032 } /* code 0032 */
  ,{   6,   6,  1, acGUI_FontArial14_0033 } /* code 0033 */
  ,{   6,   6,  1, acGUI_FontArial14_0034 } /* code 0034 */
  ,{   6,   6,  1, acGUI_FontArial14_0035 } /* code 0035 */
  ,{   6,   6,  1, acGUI_FontArial14_0036 } /* code 0036 */
  ,{   6,   6,  1, acGUI_FontArial14_0037 } /* code 0037 */
  ,{   6,   6,  1, acGUI_FontArial14_0038 } /* code 0038 */
  ,{   6,   6,  1, acGUI_FontArial14_0039 } /* code 0039 */
  ,{   3,   3,  1, acGUI_FontArial14_003A } /* code 003A */
  ,{   3,   3,  1, acGUI_FontArial14_003B } /* code 003B */
  ,{   6,   6,  1, acGUI_FontArial14_003C } /* code 003C */
  ,{   6,   6,  1, acGUI_FontArial14_003D } /* code 003D */
  ,{   6,   6,  1, acGUI_FontArial14_003E } /* code 003E */
  ,{   6,   6,  1, acGUI_FontArial14_003F } /* code 003F */
  ,{  11,  11,  2, acGUI_FontArial14_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_FontArial14_0041 } /* code 0041 */
  ,{   7,   7,  1, acGUI_FontArial14_0042 } /* code 0042 */
  ,{   7,   7,  1, acGUI_FontArial14_0043 } /* code 0043 */
  ,{   7,   7,  1, acGUI_FontArial14_0044 } /* code 0044 */
  ,{   6,   6,  1, acGUI_FontArial14_0045 } /* code 0045 */
  ,{   6,   6,  1, acGUI_FontArial14_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontArial14_0047 } /* code 0047 */
  ,{   7,   7,  1, acGUI_FontArial14_0048 } /* code 0048 */
  ,{   2,   2,  1, acGUI_FontArial14_0049 } /* code 0049 */
  ,{   5,   5,  1, acGUI_FontArial14_004A } /* code 004A */
  ,{   7,   7,  1, acGUI_FontArial14_004B } /* code 004B */
  ,{   6,   6,  1, acGUI_FontArial14_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_FontArial14_004D } /* code 004D */
  ,{   7,   7,  1, acGUI_FontArial14_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_FontArial14_004F } /* code 004F */
  ,{   6,   6,  1, acGUI_FontArial14_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontArial14_0051 } /* code 0051 */
  ,{   7,   7,  1, acGUI_FontArial14_0052 } /* code 0052 */
  ,{   7,   7,  1, acGUI_FontArial14_0053 } /* code 0053 */
  ,{   6,   6,  1, acGUI_FontArial14_0054 } /* code 0054 */
  ,{   7,   7,  1, acGUI_FontArial14_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_FontArial14_0056 } /* code 0056 */
  ,{  10,  10,  2, acGUI_FontArial14_0057 } /* code 0057 */
  ,{   7,   7,  1, acGUI_FontArial14_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontArial14_0059 } /* code 0059 */
  ,{   7,   7,  1, acGUI_FontArial14_005A } /* code 005A */
  ,{   3,   3,  1, acGUI_FontArial14_005B } /* code 005B */
  ,{   3,   3,  1, acGUI_FontArial14_005C } /* code 005C */
  ,{   3,   3,  1, acGUI_FontArial14_005D } /* code 005D */
  ,{   5,   5,  1, acGUI_FontArial14_005E } /* code 005E */
  ,{   6,   6,  1, acGUI_FontArial14_005F } /* code 005F */
  ,{   4,   4,  1, acGUI_FontArial14_0060 } /* code 0060 */
  ,{   6,   6,  1, acGUI_FontArial14_0061 } /* code 0061 */
  ,{   6,   6,  1, acGUI_FontArial14_0062 } /* code 0062 */
  ,{   6,   6,  1, acGUI_FontArial14_0063 } /* code 0063 */
  ,{   6,   6,  1, acGUI_FontArial14_0064 } /* code 0064 */
  ,{   6,   6,  1, acGUI_FontArial14_0065 } /* code 0065 */
  ,{   4,   4,  1, acGUI_FontArial14_0066 } /* code 0066 */
  ,{   6,   6,  1, acGUI_FontArial14_0067 } /* code 0067 */
  ,{   6,   6,  1, acGUI_FontArial14_0068 } /* code 0068 */
  ,{   2,   2,  1, acGUI_FontArial14_0069 } /* code 0069 */
  ,{   2,   2,  1, acGUI_FontArial14_006A } /* code 006A */
  ,{   5,   5,  1, acGUI_FontArial14_006B } /* code 006B */
  ,{   2,   2,  1, acGUI_FontArial14_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_FontArial14_006D } /* code 006D */
  ,{   6,   6,  1, acGUI_FontArial14_006E } /* code 006E */
  ,{   6,   6,  1, acGUI_FontArial14_006F } /* code 006F */
  ,{   6,   6,  1, acGUI_FontArial14_0070 } /* code 0070 */
  ,{   6,   6,  1, acGUI_FontArial14_0071 } /* code 0071 */
  ,{   4,   4,  1, acGUI_FontArial14_0072 } /* code 0072 */
  ,{   6,   6,  1, acGUI_FontArial14_0073 } /* code 0073 */
  ,{   3,   3,  1, acGUI_FontArial14_0074 } /* code 0074 */
  ,{   6,   6,  1, acGUI_FontArial14_0075 } /* code 0075 */
  ,{   6,   6,  1, acGUI_FontArial14_0076 } /* code 0076 */
  ,{  10,  10,  2, acGUI_FontArial14_0077 } /* code 0077 */
  ,{   6,   6,  1, acGUI_FontArial14_0078 } /* code 0078 */
  ,{   6,   6,  1, acGUI_FontArial14_0079 } /* code 0079 */
  ,{   6,   6,  1, acGUI_FontArial14_007A } /* code 007A */
  ,{   4,   4,  1, acGUI_FontArial14_007B } /* code 007B */
  ,{   2,   2,  1, acGUI_FontArial14_007C } /* code 007C */
  ,{   4,   4,  1, acGUI_FontArial14_007D } /* code 007D */
  ,{   6,   6,  1, acGUI_FontArial14_007E } /* code 007E */
  ,{   8,   8,  1, acGUI_FontArial14_007F } /* code 007F */
  ,{   3,   3,  1, acGUI_FontArial14_00A0 } /* code 00A0 */
  ,{   7,   7,  1, acGUI_FontArial14_00A1 } /* code 00A1 */
  ,{   6,   6,  1, acGUI_FontArial14_00A2 } /* code 00A2 */
  ,{   5,   5,  1, acGUI_FontArial14_00A3 } /* code 00A3 */
  ,{   7,   7,  1, acGUI_FontArial14_00A4 } /* code 00A4 */
  ,{   5,   5,  1, acGUI_FontArial14_00A5 } /* code 00A5 */
  ,{   2,   2,  1, acGUI_FontArial14_00A6 } /* code 00A6 */
  ,{   6,   6,  1, acGUI_FontArial14_00A7 } /* code 00A7 */
  ,{   6,   6,  1, acGUI_FontArial14_00A8 } /* code 00A8 */
  ,{   8,   8,  1, acGUI_FontArial14_00A9 } /* code 00A9 */
  ,{   7,   7,  1, acGUI_FontArial14_00AA } /* code 00AA */
  ,{   6,   6,  1, acGUI_FontArial14_00AB } /* code 00AB */
  ,{   6,   6,  1, acGUI_FontArial14_00AC } /* code 00AC */
  ,{   4,   4,  1, acGUI_FontArial14_00AD } /* code 00AD */
  ,{   8,   8,  1, acGUI_FontArial14_00AE } /* code 00AE */
  ,{   2,   2,  1, acGUI_FontArial14_00AF } /* code 00AF */
  ,{   4,   4,  1, acGUI_FontArial14_00B0 } /* code 00B0 */
  ,{   6,   6,  1, acGUI_FontArial14_00B1 } /* code 00B1 */
  ,{   2,   2,  1, acGUI_FontArial14_00B2 } /* code 00B2 */
  ,{   2,   2,  1, acGUI_FontArial14_00B3 } /* code 00B3 */
  ,{   5,   5,  1, acGUI_FontArial14_00B4 } /* code 00B4 */
  ,{   6,   6,  1, acGUI_FontArial14_00B5 } /* code 00B5 */
  ,{   6,   6,  1, acGUI_FontArial14_00B6 } /* code 00B6 */
  ,{   4,   4,  1, acGUI_FontArial14_00B7 } /* code 00B7 */
  ,{   6,   6,  1, acGUI_FontArial14_00B8 } /* code 00B8 */
  ,{  13,  13,  2, acGUI_FontArial14_00B9 } /* code 00B9 */
  ,{   6,   6,  1, acGUI_FontArial14_00BA } /* code 00BA */
  ,{   6,   6,  1, acGUI_FontArial14_00BB } /* code 00BB */
  ,{   2,   2,  1, acGUI_FontArial14_00BC } /* code 00BC */
  ,{   7,   7,  1, acGUI_FontArial14_00BD } /* code 00BD */
  ,{   6,   6,  1, acGUI_FontArial14_00BE } /* code 00BE */
  ,{   2,   2,  1, acGUI_FontArial14_00BF } /* code 00BF */
  ,{   8,   8,  1, acGUI_FontArial14_00C0 } /* code 00C0 */
  ,{   7,   7,  1, acGUI_FontArial14_00C1 } /* code 00C1 */
  ,{   7,   7,  1, acGUI_FontArial14_00C2 } /* code 00C2 */
  ,{   6,   6,  1, acGUI_FontArial14_00C3 } /* code 00C3 */
  ,{   8,   8,  1, acGUI_FontArial14_00C4 } /* code 00C4 */
  ,{   6,   6,  1, acGUI_FontArial14_00C5 } /* code 00C5 */
  ,{  12,  12,  2, acGUI_FontArial14_00C6 } /* code 00C6 */
  ,{   7,   7,  1, acGUI_FontArial14_00C7 } /* code 00C7 */
  ,{   9,   9,  2, acGUI_FontArial14_00C8 } /* code 00C8 */
  ,{   9,   9,  2, acGUI_FontArial14_00C9 } /* code 00C9 */
  ,{   7,   7,  1, acGUI_FontArial14_00CA } /* code 00CA */
  ,{   7,   7,  1, acGUI_FontArial14_00CB } /* code 00CB */
  ,{   8,   8,  1, acGUI_FontArial14_00CC } /* code 00CC */
  ,{   7,   7,  1, acGUI_FontArial14_00CD } /* code 00CD */
  ,{   8,   8,  1, acGUI_FontArial14_00CE } /* code 00CE */
  ,{   7,   7,  1, acGUI_FontArial14_00CF } /* code 00CF */
  ,{   6,   6,  1, acGUI_FontArial14_00D0 } /* code 00D0 */
  ,{   7,   7,  1, acGUI_FontArial14_00D1 } /* code 00D1 */
  ,{   6,   6,  1, acGUI_FontArial14_00D2 } /* code 00D2 */
  ,{   7,   7,  1, acGUI_FontArial14_00D3 } /* code 00D3 */
  ,{   8,   8,  1, acGUI_FontArial14_00D4 } /* code 00D4 */
  ,{   7,   7,  1, acGUI_FontArial14_00D5 } /* code 00D5 */
  ,{   7,   7,  1, acGUI_FontArial14_00D6 } /* code 00D6 */
  ,{   6,   6,  1, acGUI_FontArial14_00D7 } /* code 00D7 */
  ,{  10,  10,  2, acGUI_FontArial14_00D8 } /* code 00D8 */
  ,{  10,  10,  2, acGUI_FontArial14_00D9 } /* code 00D9 */
  ,{   8,   8,  1, acGUI_FontArial14_00DA } /* code 00DA */
  ,{   9,   9,  2, acGUI_FontArial14_00DB } /* code 00DB */
  ,{   7,   7,  1, acGUI_FontArial14_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_FontArial14_00DD } /* code 00DD */
  ,{  11,  11,  2, acGUI_FontArial14_00DE } /* code 00DE */
  ,{   8,   8,  1, acGUI_FontArial14_00DF } /* code 00DF */
  ,{   6,   6,  1, acGUI_FontArial14_00E0 } /* code 00E0 */
  ,{   6,   6,  1, acGUI_FontArial14_00E1 } /* code 00E1 */
  ,{   7,   7,  1, acGUI_FontArial14_00E2 } /* code 00E2 */
  ,{   4,   4,  1, acGUI_FontArial14_00E3 } /* code 00E3 */
  ,{   6,   6,  1, acGUI_FontArial14_00E4 } /* code 00E4 */
  ,{   6,   6,  1, acGUI_FontArial14_00E5 } /* code 00E5 */
  ,{   8,   8,  1, acGUI_FontArial14_00E6 } /* code 00E6 */
  ,{   5,   5,  1, acGUI_FontArial14_00E7 } /* code 00E7 */
  ,{   6,   6,  1, acGUI_FontArial14_00E8 } /* code 00E8 */
  ,{   6,   6,  1, acGUI_FontArial14_00E9 } /* code 00E9 */
  ,{   5,   5,  1, acGUI_FontArial14_00EA } /* code 00EA */
  ,{   6,   6,  1, acGUI_FontArial14_00EB } /* code 00EB */
  ,{   8,   8,  1, acGUI_FontArial14_00EC } /* code 00EC */
  ,{   6,   6,  1, acGUI_FontArial14_00ED } /* code 00ED */
  ,{   6,   6,  1, acGUI_FontArial14_00EE } /* code 00EE */
  ,{   6,   6,  1, acGUI_FontArial14_00EF } /* code 00EF */
  ,{   6,   6,  1, acGUI_FontArial14_00F0 } /* code 00F0 */
  ,{   6,   6,  1, acGUI_FontArial14_00F1 } /* code 00F1 */
  ,{   6,   6,  1, acGUI_FontArial14_00F2 } /* code 00F2 */
  ,{   6,   6,  1, acGUI_FontArial14_00F3 } /* code 00F3 */
  ,{   8,   8,  1, acGUI_FontArial14_00F4 } /* code 00F4 */
  ,{   6,   6,  1, acGUI_FontArial14_00F5 } /* code 00F5 */
  ,{   6,   6,  1, acGUI_FontArial14_00F6 } /* code 00F6 */
  ,{   6,   6,  1, acGUI_FontArial14_00F7 } /* code 00F7 */
  ,{   8,   8,  1, acGUI_FontArial14_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acGUI_FontArial14_00F9 } /* code 00F9 */
  ,{   7,   7,  1, acGUI_FontArial14_00FA } /* code 00FA */
  ,{   8,   8,  1, acGUI_FontArial14_00FB } /* code 00FB */
  ,{   6,   6,  1, acGUI_FontArial14_00FC } /* code 00FC */
  ,{   6,   6,  1, acGUI_FontArial14_00FD } /* code 00FD */
  ,{   8,   8,  1, acGUI_FontArial14_00FE } /* code 00FE */
  ,{   6,   6,  1, acGUI_FontArial14_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArial14_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontArial14_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArial14_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontArial14_CharInfo[  0] /* address of first character */
  ,&GUI_FontArial14_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial14 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,14 /* height of font  */
  ,14 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArial14_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

