/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END


//#include "Main_Menu_Icon.h"
#include "Include_Lib.h"

#include "DIALOG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 1)
#define ID_EDIT_0       (GUI_ID_USER + 2)
#define ID_TEXT_1       (GUI_ID_USER + 3)
#define ID_TEXT_2       (GUI_ID_USER + 4)
#define ID_TEXT_3       (GUI_ID_USER + 5)
#define ID_TEXT_4       (GUI_ID_USER + 6)
#define ID_TEXT_5       (GUI_ID_USER + 7)
#define ID_TIMER_TIMER  (GUI_ID_USER + 8)

extern uint8_t Get_Curent_Type (void)                                                        ;
extern WM_HWIN CreateFramewinMenuDeviceListoftabls(void)                                     ;
//extern K_ModulePropertyTypedef  module_prop[]                                                ;
extern WM_HWIN CreateFramewinMenuToolsList(void)                                             ; 
extern WM_HWIN CreateWindowConfirmationScreen (void)                                         ;
extern WM_HWIN CreateFramewinMenuDeviceListoftablsAction(WM_HWIN hWinParant ,uint16_t Zone)  ;
extern WM_HWIN CreateWindowBufferAlarms(void)                                                ;
extern WM_HWIN CreateFramewinEventLog(void)                                                  ;

//extern uint8_t Get_Block (void)                                                              ;

WM_HWIN CreateWindowIconFirstMenu(void)                                                      ;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
{ FRAMEWIN_CreateIndirect,(const char *)&TextString241,   ID_FRAMEWIN_0, 25, 25, 775, 455, 0, 0x0, 0 },
{ EDIT_CreateIndirect,                        NULL, ID_EDIT_0,     100, 550,  80, 20,  0, 0x64, 0 },
{ TEXT_CreateIndirect,(const char *)&TextString1,   ID_TEXT_1, 150, 70, 110, 45, 0, 0x0, 0 },         // настройка        
{ TEXT_CreateIndirect,(const char *)&TextString2,   ID_TEXT_2, 150, 185, 170, 45, 0, 0x0, 0 },        // журнал
{ TEXT_CreateIndirect,(const char *)&TextString240, ID_TEXT_3,  543, 70, 220, 45, 0, 0x0, 0 },        //управление
{ TEXT_CreateIndirect,(const char *)&TextString62, ID_TEXT_4, 543, 185, 222, 45, 0, 0x0, 0 },         //"Буфер тревог"
{ TEXT_CreateIndirect,(const char *)&TextString460, ID_TEXT_5, 150, 300, 155, 45, 0, 0x0, 0},         //"Подтверждения"
  // USER START (Optionally insert additional widgets)
  // USER END"Подтверждения"
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


 
static void _cbFrameWinVideo(WM_MESSAGE* pMsg) {
  WM_HWIN hWin;
  WM_HWIN hText;
  int     IsCompletelyVis;
  int     IsCompletelyCovered;

  switch (pMsg->MsgId) {
  case WM_PAINT:
  //  if (_IsCompletelyVis) {
      GUI_SetBkColor(GUI_DARKGREEN);
      GUI_Clear();
      GUI_SetColor(GUI_WHITE);
      GUI_DispStringAt("Completely visible", 5, 5);
  //  } else {
     
//    }
    break;
  case WM_NOTIFY_VIS_CHANGED:
     GUI_SetBkColor(GUI_GRAY);
      GUI_Clear();
      GUI_SetColor(GUI_WHITE);
      GUI_DispStringAt("Not completely visible", 5, 5);
 /*   hText = WM_GetDialogItem(WM_HBKWIN, GUI_ID_TEXT1);
    hWin  = WM_GetClientWindow(pMsg.hWin);
    IsCompletelyVis     = WM_IsCompletelyVisible(hWin);
    IsCompletelyCovered = WM_IsCompletelyCovered(hWin);
    if (IsCompletelyCovered) {
      TEXT_SetText(hText, "completely\ncovered");
    } else {
      TEXT_SetText(hText, "not completely\ncovered");
    }
    if (_IsCompletelyVis != IsCompletelyVis) {
      _IsCompletelyVis = IsCompletelyVis;
      WM_InvalidateWindow(hWin);    /* Only required if content changes if partially hidden */
   // }*/
    break;
  default:
    WM_DefaultProc(pMsg);
  }
}
WM_HWIN CreateWindowIconFirstMenu1(void) {
  WM_HWIN hWinVideo;

 // if(Check_GUI_RAM())
 // {
  //  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),_cbDialog, WM_HBKWIN,0,0);     
  hWinVideo = FRAMEWIN_CreateEx(5, 5, 500, 300, 0, WM_CF_SHOW, FRAMEWIN_CF_MOVEABLE, 0, "Video window", _cbFrameWinVideo);
    FRAMEWIN_SetClientColor(hWinVideo, GUI_INVALID_COLOR);
  //}
  return hWinVideo;
}

/*************************** End of file ****************************/
