
#ifndef  __DESCRIPTION_OF_EVENTS_H
#define  __DESCRIPTION_OF_EVENTS_H

#include "Event_Types_Public.h"
#include "System_Text_Extern.h"

#define IND_AI                                                    1000U


const TypeEvents_t  EventTypeTable [] ={
  [IND_AI+1] = TYPE_EVENT_FAULT , 
  [IND_AI+2] = TYPE_EVENT_FAULT , 
  [IND_AI+3] = TYPE_EVENT_FAULT , 
  [IND_AI+4] = TYPE_EVENT_FAULT , 
  [IND_AI+5] = TYPE_EVENT_FAULT , 
  [IND_AI+6] = TYPE_EVENT_FAULT , 
  [IND_AI+7] = TYPE_EVENT_FAULT , 
  [IND_AI+8] = TYPE_EVENT_FAULT , 
  [IND_AI+9] = TYPE_EVENT_FAULT , 
  [IND_AI+10] = TYPE_EVENT_FAULT , 
  [IND_AI+11] = TYPE_EVENT_FAULT , 
  [IND_AI+12] = TYPE_EVENT_FAULT , 
  [IND_AI+13] = TYPE_EVENT_FAULT , 
  [IND_AI+14] = TYPE_EVENT_FAULT , 
  [IND_AI+15] = TYPE_EVENT_FAULT ,  
  [IND_AI+16] = TYPE_EVENT_FAULT ,
  
  [IND_AI+32] = TYPE_EVENT_FAULT ,
  [IND_AI+33] = TYPE_EVENT_FAULT ,
  [IND_AI+34] = TYPE_EVENT_FAULT ,
  [IND_AI+35] = TYPE_EVENT_FAULT ,
  [IND_AI+36] = TYPE_EVENT_FAULT ,
  
  [IND_AI+41] = TYPE_EVENT_FAULT ,
  
  [IND_AI+51] = TYPE_EVENT_FAULT ,
  [IND_AI+52] = TYPE_EVENT_FAULT ,
  [IND_AI+53] = TYPE_EVENT_FAULT ,
  [IND_AI+54] = TYPE_EVENT_FAULT ,
  [IND_AI+55] = TYPE_EVENT_FAULT ,
  
  [IND_AI+71] = TYPE_EVENT_FAULT ,
  
   
  [IND_AI+73] = TYPE_EVENT_FAULT ,
  [IND_AI+74] = TYPE_EVENT_FAULT ,
  [IND_AI+75] = TYPE_EVENT_FAULT ,
  
  [IND_AI+101] = TYPE_EVENT_SEVICE ,
  [IND_AI+102] = TYPE_EVENT_SEVICE ,
  [IND_AI+103] = TYPE_EVENT_FAULT ,
  [IND_AI+104] = TYPE_EVENT_SEVICE ,
  [IND_AI+105] = TYPE_EVENT_FAULT ,
  [IND_AI+106] = TYPE_EVENT_SEVICE ,
  [IND_AI+107] = TYPE_EVENT_SEVICE ,
  [IND_AI+108] = TYPE_EVENT_SEVICE ,
  [IND_AI+109] = TYPE_EVENT_SEVICE ,  
  [IND_AI+110] = TYPE_EVENT_FAULT ,
  [IND_AI+111] = TYPE_EVENT_FAULT ,
  [IND_AI+112] = TYPE_EVENT_FAULT ,
  [IND_AI+113] = TYPE_EVENT_FAULT ,
  [IND_AI+114] = TYPE_EVENT_FAULT ,
  
  [IND_AI+120] = TYPE_EVENT_FAULT ,
  [IND_AI+121] = TYPE_EVENT_FAULT ,
  [IND_AI+122] = TYPE_EVENT_NORMA ,
  [IND_AI+123] = TYPE_EVENT_FAULT ,
  [IND_AI+124] = TYPE_EVENT_FAULT ,
  [IND_AI+125] = TYPE_EVENT_FAULT ,
  [IND_AI+126] = TYPE_EVENT_FAULT ,
  [IND_AI+127] = TYPE_EVENT_FAULT ,
  [IND_AI+128] = TYPE_EVENT_FAULT ,
  [IND_AI+129] = TYPE_EVENT_FAULT ,
  [IND_AI+130] = TYPE_EVENT_FAULT ,
  [IND_AI+131] = TYPE_EVENT_FAULT ,
  [IND_AI+132] = TYPE_EVENT_SEVICE ,
  [IND_AI+133] = TYPE_EVENT_FAULT , 
  [IND_AI+134] = TYPE_EVENT_FAULT , 
  [IND_AI+135] = TYPE_EVENT_FAULT , 
  [IND_AI+136] = TYPE_EVENT_SEVICE , 
  [IND_AI+137] = TYPE_EVENT_FAULT , 
  [IND_AI+138] = TYPE_EVENT_FAULT , 
  [IND_AI+139] = TYPE_EVENT_FAULT , 
  [IND_AI+140] = TYPE_EVENT_SEVICE , 
  [IND_AI+141] = TYPE_EVENT_FAULT , 
  [IND_AI+142] = TYPE_EVENT_FAULT , 
  [IND_AI+143] = TYPE_EVENT_FAULT , 
  [IND_AI+144] = TYPE_EVENT_FAULT , 
  [IND_AI+145] = TYPE_EVENT_FAULT , 
  [IND_AI+146] = TYPE_EVENT_FAULT , 
  [IND_AI+147] = TYPE_EVENT_FAULT , 
  [IND_AI+148] = TYPE_EVENT_FAULT , 
  [IND_AI+149] = TYPE_EVENT_SEVICE , 
  [IND_AI+150] = TYPE_EVENT_SEVICE ,
  [IND_AI+151] = TYPE_EVENT_FAULT , 
  [IND_AI+152] = TYPE_EVENT_FAULT ,
  [IND_AI+153] = TYPE_EVENT_SEVICE ,
  [IND_AI+154] = TYPE_EVENT_SEVICE ,
  [IND_AI+155] = TYPE_EVENT_SEVICE ,
  [IND_AI+156] = TYPE_EVENT_FAULT ,
  [IND_AI+157] = TYPE_EVENT_FAULT ,
  [IND_AI+158] = TYPE_EVENT_FAULT ,
  [IND_AI+159] = TYPE_EVENT_SEVICE ,
  
  [IND_AI+170] = TYPE_EVENT_FAULT ,
  [IND_AI+180] = TYPE_EVENT_FAULT ,
  [IND_AI+181] = TYPE_EVENT_SEVICE ,
  [IND_AI+182] = TYPE_EVENT_FAULT ,
  [IND_AI+183] = TYPE_EVENT_FAULT ,
  [IND_AI+184] = TYPE_EVENT_FAULT ,
  [IND_AI+185] = TYPE_EVENT_FAULT ,
  [IND_AI+186] = TYPE_EVENT_FAULT ,
 
} ; 




const char  * TextDescriptionOfEvents [ ] ={
  
  [IND_AI+1] = (const char *)&TextStringEvent1001 , 
  [IND_AI+2] = (const char *)&TextStringEvent1002 , 
  [IND_AI+3] = (const char *)&TextStringEvent1003 , 
  [IND_AI+4] = (const char *)&TextStringEvent1004 , 
  [IND_AI+5] = (const char *)&TextStringEvent1005 , 
  [IND_AI+6] = (const char *)&TextStringEvent1006 , 
  [IND_AI+7] = (const char *)&TextStringEvent1007 , 
  [IND_AI+8] = (const char *)&TextStringEvent1008 , 
  [IND_AI+9] = (const char *)&TextStringEvent1009 , 
  [IND_AI+10] = (const char *)&TextStringEvent1010 , 
  [IND_AI+11] = (const char *)&TextStringEvent1011 , 
  [IND_AI+12] = (const char *)&TextStringEvent1012 , 
  [IND_AI+13] = (const char *)&TextStringEvent1013 , 
  [IND_AI+14] = (const char *)&TextStringEvent1014 , 
  [IND_AI+15] = (const char *)&TextStringEvent1015 ,  
  [IND_AI+16] = (const char *)&TextStringEvent1016 ,
  
  [IND_AI+32] = (const char *)&TextStringEvent1032 ,
  [IND_AI+33] = (const char *)&TextStringEvent1033 ,
  [IND_AI+34] = (const char *)&TextStringEvent1034 ,
  [IND_AI+35] = (const char *)&TextStringEvent1035 ,
  [IND_AI+36] = (const char *)&TextStringEvent1036 ,
  
  [IND_AI+41] = (const char *)&TextStringEvent1041 ,
  
  [IND_AI+51] = (const char *)&TextStringEvent1051 ,
  [IND_AI+52] = (const char *)&TextStringEvent1052 ,
  [IND_AI+53] = (const char *)&TextStringEvent1053 ,
  [IND_AI+54] = (const char *)&TextStringEvent1054 ,
  [IND_AI+55] = (const char *)&TextStringEvent1055 ,
  
  [IND_AI+71] = (const char *)&TextStringEvent1071 ,
  
   
  [IND_AI+73] = (const char *)&TextStringEvent1073 ,
  [IND_AI+74] = (const char *)&TextStringEvent1074 ,
  [IND_AI+75] = (const char *)&TextStringEvent1075 ,
  
  [IND_AI+101] = (const char *)&TextStringEvent1101 ,
  [IND_AI+102] = (const char *)&TextStringEvent1102 ,
  [IND_AI+103] = (const char *)&TextStringEvent1103 ,
  [IND_AI+104] = (const char *)&TextStringEvent1104 ,
  [IND_AI+105] = (const char *)&TextStringEvent1105 ,
  [IND_AI+106] = (const char *)&TextStringEvent1106 ,
  [IND_AI+107] = (const char *)&TextStringEvent1107 ,
  [IND_AI+108] = (const char *)&TextStringEvent1108 ,
  [IND_AI+109] = (const char *)&TextStringEvent1109 ,  
  [IND_AI+110] = (const char *)&TextStringEvent1110 ,
  [IND_AI+111] = (const char *)&TextStringEvent1111 ,
  [IND_AI+112] = (const char *)&TextStringEvent1112 ,
  [IND_AI+113] = (const char *)&TextStringEvent1113 ,
  [IND_AI+114] = (const char *)&TextStringEvent1114 ,
  
  [IND_AI+120] = (const char *)&TextStringEvent1120 ,
  [IND_AI+121] = (const char *)&TextStringEvent1121 ,
  [IND_AI+122] = (const char *)&TextStringEvent1122 ,
  [IND_AI+123] = (const char *)&TextStringEvent1123 ,
  [IND_AI+124] = (const char *)&TextStringEvent1124 ,
  [IND_AI+125] = (const char *)&TextStringEvent1125 ,
  [IND_AI+126] = (const char *)&TextStringEvent1126 ,
  [IND_AI+127] = (const char *)&TextStringEvent1127 ,
  [IND_AI+128] = (const char *)&TextStringEvent1128 ,
  [IND_AI+129] = (const char *)&TextStringEvent1129 ,
  [IND_AI+130] = (const char *)&TextStringEvent1130 ,
  [IND_AI+131] = (const char *)&TextStringEvent1131 ,
  [IND_AI+132] = (const char *)&TextStringEvent1132 ,
  [IND_AI+133] = (const char *)&TextStringEvent1133 , 
  [IND_AI+134] = (const char *)&TextStringEvent1134 , 
  [IND_AI+135] = (const char *)&TextStringEvent1135 , 
  [IND_AI+136] = (const char *)&TextStringEvent1136 , 
  [IND_AI+137] = (const char *)&TextStringEvent1137 , 
  [IND_AI+138] = (const char *)&TextStringEvent1138 , 
  [IND_AI+139] = (const char *)&TextStringEvent1139 , 
  [IND_AI+140] = (const char *)&TextStringEvent1140 , 
  [IND_AI+141] = (const char *)&TextStringEvent1141 , 
  [IND_AI+142] = (const char *)&TextStringEvent1142 , 
  [IND_AI+143] = (const char *)&TextStringEvent1143 , 
  [IND_AI+144] = (const char *)&TextStringEvent1144 , 
  [IND_AI+145] = (const char *)&TextStringEvent1145 , 
  [IND_AI+146] = (const char *)&TextStringEvent1146 , 
  [IND_AI+147] = (const char *)&TextStringEvent1147 , 
  [IND_AI+148] = (const char *)&TextStringEvent1148 , 
  [IND_AI+149] = (const char *)&TextStringEvent1149 , 
  [IND_AI+150] = (const char *)&TextStringEvent1150 ,
  [IND_AI+151] = (const char *)&TextStringEvent1151 , 
  [IND_AI+152] = (const char *)&TextStringEvent1152 ,
  [IND_AI+153] = (const char *)&TextStringEvent1153 ,
  [IND_AI+154] = (const char *)&TextStringEvent1154 ,
  [IND_AI+155] = (const char *)&TextStringEvent1155 ,
  [IND_AI+156] = (const char *)&TextStringEvent1156 ,
  [IND_AI+157] = (const char *)&TextStringEvent1157 ,
  [IND_AI+158] = (const char *)&TextStringEvent1158 ,
  [IND_AI+159] = (const char *)&TextStringEvent1159 ,
  
  [IND_AI+170] = (const char *)&TextStringEvent1170 ,
  [IND_AI+180] = (const char *)&TextStringEvent1180 ,
  [IND_AI+181] = (const char *)&TextStringEvent1181 ,
  [IND_AI+182] = (const char *)&TextStringEvent1182 ,
  [IND_AI+183] = (const char *)&TextStringEvent1183 ,
  [IND_AI+184] = (const char *)&TextStringEvent1184 ,
  [IND_AI+185] = (const char *)&TextStringEvent1185 ,
  [IND_AI+186] = (const char *)&TextStringEvent1186 , 
  

};
#endif