#ifndef  __SYSTEM_TEXT_EXTERN_H
#define  __SYSTEM_TEXT_EXTERN_H

#include <stdlib.h>
#include "Added_Fonts.h"

 extern const unsigned char  TextString1[] ;   
 extern const unsigned char  TextString2[] ;
 extern const unsigned char  TextString3[] ;
 extern const unsigned char  TextString4[] ;   
 extern const unsigned char  TextString5[] ;
 extern const unsigned char  TextString6[] ;
 extern const unsigned char  TextString7[] ;   
 extern const unsigned char  TextString8[] ;
 extern const unsigned char  TextString9[] ;
 extern const unsigned char  TextString10[] ;   
 extern const unsigned char  TextString11[] ;
 extern const unsigned char  TextString12[] ;
 extern const unsigned char  TextString13[] ;   
 extern const unsigned char  TextString14[] ;
 extern const unsigned char  TextString15[] ;
 extern const unsigned char  TextString16[] ;   
 extern const unsigned char  TextString17[] ;
 extern const unsigned char  TextString18[] ;
 extern const unsigned char  TextString19[] ;   
 extern const unsigned char  TextString20[] ;
 extern const unsigned char  TextString21[] ;
 extern const unsigned char  TextString22[] ;   
 extern const unsigned char  TextString23[] ;
 extern const unsigned char  TextString24[] ;
 extern const unsigned char  TextString25[] ;   
 extern const unsigned char  TextString26[] ;
 extern const unsigned char  TextString27[] ;
 extern const unsigned char  TextString28[] ;   
 extern const unsigned char  TextString29[] ;
 extern const unsigned char  TextString30[] ;
 extern const unsigned char  TextString31[] ;   
 extern const unsigned char  TextString32[] ;
 extern const unsigned char  TextString33[] ;
 extern const unsigned char  TextString34[] ;   
 extern const unsigned char  TextString35[] ;
 extern const unsigned char  TextString36[] ;
 extern const unsigned char  TextString37[] ;   
 extern const unsigned char  TextString38[] ;
 extern const unsigned char  TextString39[] ;
 extern const unsigned char  TextString40[] ;   
 extern const unsigned char  TextString41[] ;
 extern const unsigned char  TextString42[] ;
 extern const unsigned char  TextString43[] ;   
 extern const unsigned char  TextString44[] ;
 //extern const unsigned char  TextString45[] ;
 extern const unsigned char  TextString46[] ;   
 extern const unsigned char  TextString47[] ;
// extern const unsigned char  TextString48[] ;
// extern const unsigned char  TextString49[] ;   
 extern const unsigned char  TextString50[] ;
 extern const unsigned char  TextString51[] ;
 extern const unsigned char  TextString52[] ;   
 extern const unsigned char  TextString53[] ;
 extern const unsigned char  TextString54[] ;
 extern const unsigned char  TextString55[] ;   
 extern const unsigned char  TextString56[] ;
 extern const unsigned char  TextString57[] ;
 extern const unsigned char  TextString58[] ;   
 extern const unsigned char  TextString59[] ;
 extern const unsigned char  TextString60[] ;
 extern const unsigned char  TextString61[] ;   
 extern const unsigned char  TextString62[] ;
 extern const unsigned char  TextString63[] ;
 extern const unsigned char  TextString64[] ;   
 extern const unsigned char  TextString65[] ;
 extern const unsigned char  TextString66[] ;
 extern const unsigned char  TextString67[] ;   
 extern const unsigned char  TextString68[] ;
 extern const unsigned char  TextString69[] ;
 extern const unsigned char  TextString70[] ;   
 extern const unsigned char  TextString71[] ;
 extern const unsigned char  TextString72[] ;
// extern const unsigned char  TextString73[] ;   
 extern const unsigned char  TextString74[] ;
 extern const unsigned char  TextString75[] ;
 extern const unsigned char  TextString76[] ;   
 extern const unsigned char  TextString77[] ;
 extern const unsigned char  TextString78[] ;
 extern const unsigned char  TextString79[] ;   
 extern const unsigned char  TextString80[] ;
 extern const unsigned char  TextString81[] ;
 extern const unsigned char  TextString82[] ;   
 extern const unsigned char  TextString83[] ;
 extern const unsigned char  TextString84[] ;
 extern const unsigned char  TextString85[] ;   
 extern const unsigned char  TextString86[] ;
 extern const unsigned char  TextString87[] ;
 extern const unsigned char  TextString88[] ;   
 extern const unsigned char  TextString89[] ;
 extern const unsigned char  TextString90[] ;
 extern const unsigned char  TextString91[] ;   
 extern const unsigned char  TextString92[] ;
 extern const unsigned char  TextString93[] ;
 extern const unsigned char  TextString94[] ;   
 extern const unsigned char  TextString95[] ;
 extern const unsigned char  TextString96[] ;
 extern const unsigned char  TextString97[] ;   
 extern const unsigned char  TextString98[] ;
 extern const unsigned char  TextString99[] ;
 extern const unsigned char  TextString100[] ;   
 extern const unsigned char  TextString101[] ;
 extern const unsigned char  TextString102[] ;
 extern const unsigned char  TextString103[] ;   
 extern const unsigned char  TextString104[] ;
 extern const unsigned char  TextString105[] ;
 extern const unsigned char  TextString105[] ;
 extern const unsigned char  TextString106[] ;
 extern const unsigned char  TextString107[] ;   
 extern const unsigned char  TextString108[] ;
 extern const unsigned char  TextString109[] ;
 extern const unsigned char  TextString110[] ;   
 extern const unsigned char  TextString111[] ;
 extern const unsigned char  TextString112[] ;
 extern const unsigned char  TextString113[] ;   
 extern const unsigned char  TextString114[] ;
 extern const unsigned char  TextString115[] ;
 extern const unsigned char  TextString116[] ;   
 extern const unsigned char  TextString117[] ;
 extern const unsigned char  TextString118[] ;
 extern const unsigned char  TextString119[] ;   
 extern const unsigned char  TextString120[] ;
 extern const unsigned char  TextString121[] ;
 extern const unsigned char  TextString122[] ;   
 extern const unsigned char  TextString123[] ;
 extern const unsigned char  TextString124[] ;
 extern const unsigned char  TextString125[] ;   
 extern const unsigned char  TextString126[] ;
 extern const unsigned char  TextString127[] ;
 extern const unsigned char  TextString128[] ;   
 extern const unsigned char  TextString129[] ;
 extern const unsigned char  TextString130[] ;
 extern const unsigned char  TextString131[] ;   
 extern const unsigned char  TextString132[] ;
 extern const unsigned char  TextString133[] ;
 extern const unsigned char  TextString134[] ;   
 extern const unsigned char  TextString135[] ;
 extern const unsigned char  TextString136[] ;
 extern const unsigned char  TextString137[] ;   
 extern const unsigned char  TextString138[] ;
 extern const unsigned char  TextString139[] ;
 extern const unsigned char  TextString140[] ;   
 extern const unsigned char  TextString141[] ;
 extern const unsigned char  TextString142[] ;
 extern const unsigned char  TextString143[] ;   
 extern const unsigned char  TextString144[] ;
 extern const unsigned char  TextString145[] ;
 extern const unsigned char  TextString146[] ;   
 extern const unsigned char  TextString147[] ;
 extern const unsigned char  TextString148[] ;
 extern const unsigned char  TextString149[] ;   
 extern const unsigned char  TextString150[] ;
 extern const unsigned char  TextString151[] ;
 extern const unsigned char  TextString152[] ;   
 extern const unsigned char  TextString153[] ;
 extern const unsigned char  TextString154[] ;
 extern const unsigned char  TextString155[] ;   
 extern const unsigned char  TextString156[] ;
 extern const unsigned char  TextString157[] ;
 extern const unsigned char  TextString158[] ;   
 extern const unsigned char  TextString159[] ;
 extern const unsigned char  TextString160[] ;
 extern const unsigned char  TextString161[] ;   
 extern const unsigned char  TextString162[] ;
 extern const unsigned char  TextString163[] ;
 extern const unsigned char  TextString164[] ;   
 extern const unsigned char  TextString165[] ;
 extern const unsigned char  TextString166[] ;
 extern const unsigned char  TextString167[] ;   
 extern const unsigned char  TextString168[] ;
 extern const unsigned char  TextString169[] ;
 extern const unsigned char  TextString170[] ;   
 extern const unsigned char  TextString171[] ;
 extern const unsigned char  TextString172[] ;
 extern const unsigned char  TextString173[] ;   
 extern const unsigned char  TextString174[] ;
 extern const unsigned char  TextString175[] ;
 extern const unsigned char  TextString176[] ;   
 extern const unsigned char  TextString177[] ;
 extern const unsigned char  TextString178[] ;
 extern const unsigned char  TextString179[] ;   
 extern const unsigned char  TextString180[] ;
 extern const unsigned char  TextString181[] ;
 extern const unsigned char  TextString182[] ;   
 extern const unsigned char  TextString183[] ;
 extern const unsigned char  TextString184[] ;
 extern const unsigned char  TextString185[] ;   
 extern const unsigned char  TextString186[] ;
 extern const unsigned char  TextString187[] ;
 extern const unsigned char  TextString188[] ;   
 extern const unsigned char  TextString189[] ;
 extern const unsigned char  TextString190[] ;
 extern const unsigned char  TextString191[] ;   
 extern const unsigned char  TextString192[] ;
 extern const unsigned char  TextString193[] ;
 extern const unsigned char  TextString194[] ;   
 extern const unsigned char  TextString195[] ;
 extern const unsigned char  TextString196[] ;
 extern const unsigned char  TextString197[] ;   
 extern const unsigned char  TextString198[] ;
 extern const unsigned char  TextString199[] ;
 extern const unsigned char  TextString200[] ;
 extern const unsigned char  TextString201[] ;   
 extern const unsigned char  TextString202[] ;
 extern const unsigned char  TextString203[] ;
 extern const unsigned char  TextString204[] ;   
 extern const unsigned char  TextString205[] ;
 extern const unsigned char  TextString206[] ;
 extern const unsigned char  TextString207[] ;   
 extern const unsigned char  TextString208[] ;
 extern const unsigned char  TextString209[] ;
 extern const unsigned char  TextString210[] ;   
 extern const unsigned char  TextString211[] ;
 extern const unsigned char  TextString212[] ;
 extern const unsigned char  TextString213[] ;   
 extern const unsigned char  TextString214[] ;
 extern const unsigned char  TextString215[] ;
 extern const unsigned char  TextString216[] ;   
 extern const unsigned char  TextString217[] ;
 extern const unsigned char  TextString218[] ;
 extern const unsigned char  TextString219[] ;   
 extern const unsigned char  TextString220[] ;
 extern const unsigned char  TextString221[] ;
 extern const unsigned char  TextString222[] ;   
 extern const unsigned char  TextString223[] ;
 extern const unsigned char  TextString224[] ;
 extern const unsigned char  TextString225[] ;   
 extern const unsigned char  TextString226[] ;
 extern const unsigned char  TextString227[] ;
 extern const unsigned char  TextString228[] ;   
 extern const unsigned char  TextString229[] ;
 extern const unsigned char  TextString230[] ;
 extern const unsigned char  TextString231[] ;   
 extern const unsigned char  TextString232[] ;
 extern const unsigned char  TextString233[] ;
 extern const unsigned char  TextString234[] ;   
 extern const unsigned char  TextString235[] ;
 extern const unsigned char  TextString236[] ;
 extern const unsigned char  TextString237[] ;   
 extern const unsigned char  TextString238[] ;
 extern const unsigned char  TextString239[] ;
 extern const unsigned char  TextString240[] ;   
 extern const unsigned char  TextString241[] ;
 extern const unsigned char  TextString242[] ;
 extern const unsigned char  TextString243[] ;   
 extern const unsigned char  TextString244[] ;
 extern const unsigned char  TextString245[] ;
 extern const unsigned char  TextString246[] ;   
 extern const unsigned char  TextString247[] ;
 extern const unsigned char  TextString248[] ;
 extern const unsigned char  TextString249[] ;   
 extern const unsigned char  TextString250[] ;
 extern const unsigned char  TextString251[] ;
 extern const unsigned char  TextString252[] ;   
 extern const unsigned char  TextString253[] ;
 extern const unsigned char  TextString254[] ;
 extern const unsigned char  TextString255[] ;   
 extern const unsigned char  TextString256[] ;
 extern const unsigned char  TextString257[] ;
 extern const unsigned char  TextString258[] ;   
 extern const unsigned char  TextString259[] ;
 extern const unsigned char  TextString260[] ;
 extern const unsigned char  TextString261[] ;   
 extern const unsigned char  TextString262[] ;
 extern const unsigned char  TextString263[] ;
 extern const unsigned char  TextString264[] ;   
 extern const unsigned char  TextString265[] ;
 extern const unsigned char  TextString266[] ;
 extern const unsigned char  TextString267[] ;   
 extern const unsigned char  TextString268[] ;
 extern const unsigned char  TextString269[] ;
 extern const unsigned char  TextString270[] ;   
 extern const unsigned char  TextString271[] ;
 extern const unsigned char  TextString272[] ;
 extern const unsigned char  TextString273[] ;   
 extern const unsigned char  TextString274[] ;
 extern const unsigned char  TextString275[] ;
 extern const unsigned char  TextString276[] ;   
 extern const unsigned char  TextString277[] ;
 extern const unsigned char  TextString278[] ;
 extern const unsigned char  TextString279[] ;   
 extern const unsigned char  TextString280[] ;
 extern const unsigned char  TextString281[] ;
 extern const unsigned char  TextString282[] ;   
 extern const unsigned char  TextString283[] ;
 extern const unsigned char  TextString284[] ;
 extern const unsigned char  TextString285[] ;   
 extern const unsigned char  TextString286[] ;
 extern const unsigned char  TextString287[] ;
 extern const unsigned char  TextString288[] ;   
 extern const unsigned char  TextString289[] ;
// extern const unsigned char  TextString290[] ;
 extern const unsigned char  TextString291[] ;   
 //extern const unsigned char  TextString292[] ;
 extern const unsigned char  TextString293[] ;
 extern const unsigned char  TextString294[] ;   
 extern const unsigned char  TextString295[] ;
 extern const unsigned char  TextString296[] ;
 extern const unsigned char  TextString297[] ;   
 extern const unsigned char  TextString298[] ;
 extern const unsigned char  TextString299[] ;
 
 extern const unsigned char  TextString300[] ;   
 extern const unsigned char  TextString301[] ;
 extern const unsigned char  TextString302[] ;
 extern const unsigned char  TextString303[] ;   
 extern const unsigned char  TextString304[] ;
 extern const unsigned char  TextString305[] ;
 extern const unsigned char  TextString306[] ;   
 extern const unsigned char  TextString307[] ;
 extern const unsigned char  TextString308[] ;
 extern const unsigned char  TextString309[] ;   
 extern const unsigned char  TextString310[] ;
 extern const unsigned char  TextString311[] ;
 extern const unsigned char  TextString312[] ;   
 extern const unsigned char  TextString313[] ;
 extern const unsigned char  TextString314[] ;
 extern const unsigned char  TextString315[] ;   
 extern const unsigned char  TextString316[] ;
 extern const unsigned char  TextString317[] ;
 extern const unsigned char  TextString318[] ;
 extern const unsigned char  TextString319[] ;
 extern const unsigned char  TextString320[] ;
 extern const unsigned char  TextString321[] ;
 extern const unsigned char  TextString322[] ;   
 extern const unsigned char  TextString323[] ;
 extern const unsigned char  TextString324[] ;
 extern const unsigned char  TextString325[] ;   
 extern const unsigned char  TextString326[] ;
 extern const unsigned char  TextString327[] ;
 extern const unsigned char  TextString328[] ;   
 extern const unsigned char  TextString329[] ;
 extern const unsigned char  TextString330[] ;
 extern const unsigned char  TextString331[] ;   
 extern const unsigned char  TextString332[] ;
 extern const unsigned char  TextString333[] ;
 extern const unsigned char  TextString334[] ;   
 extern const unsigned char  TextString335[] ;
 extern const unsigned char  TextString336[] ;
 extern const unsigned char  TextString337[] ;   
 extern const unsigned char  TextString338[] ;
 extern const unsigned char  TextString339[] ;
 extern const unsigned char  TextString340[] ;   
 extern const unsigned char  TextString341[] ;
 extern const unsigned char  TextString342[] ;
 extern const unsigned char  TextString343[] ;   
 extern const unsigned char  TextString344[] ;
 extern const unsigned char  TextString345[] ;
 extern const unsigned char  TextString346[] ;   
 extern const unsigned char  TextString347[] ;
 extern const unsigned char  TextString348[] ;
 extern const unsigned char  TextString349[] ;   
 extern const unsigned char  TextString350[] ;
 extern const unsigned char  TextString351[] ;
 extern const unsigned char  TextString352[] ;   
 extern const unsigned char  TextString353[] ;
 extern const unsigned char  TextString354[] ;
 extern const unsigned char  TextString355[] ;   
 extern const unsigned char  TextString356[] ;
 extern const unsigned char  TextString357[] ;
 extern const unsigned char  TextString358[] ;   
 extern const unsigned char  TextString359[] ;
// extern const unsigned char  TextString360[] ;
 extern const unsigned char  TextString361[] ;   
 extern const unsigned char  TextString362[] ;
 extern const unsigned char  TextString363[] ;
 extern const unsigned char  TextString364[] ;   
 extern const unsigned char  TextString365[] ;
 extern const unsigned char  TextString366[] ;
 extern const unsigned char  TextString367[] ;   
 extern const unsigned char  TextString368[] ;
 extern const unsigned char  TextString369[] ;
 extern const unsigned char  TextString370[] ;   
 extern const unsigned char  TextString371[] ;
 extern const unsigned char  TextString372[] ;
 extern const unsigned char  TextString373[] ;   
 extern const unsigned char  TextString374[] ;
 extern const unsigned char  TextString375[] ;
 extern const unsigned char  TextString376[] ;   
 extern const unsigned char  TextString377[] ;
 extern const unsigned char  TextString378[] ;
 extern const unsigned char  TextString379[] ;   
 extern const unsigned char  TextString380[] ;
 extern const unsigned char  TextString381[] ;
 extern const unsigned char  TextString382[] ;   
 extern const unsigned char  TextString383[] ;
 extern const unsigned char  TextString384[] ;
 extern const unsigned char  TextString385[] ;   
 extern const unsigned char  TextString386[] ;
 extern const unsigned char  TextString387[] ;
 extern const unsigned char  TextString388[] ;   
 extern const unsigned char  TextString389[] ;
 extern const unsigned char  TextString390[] ;
 extern const unsigned char  TextString391[] ;   
 extern const unsigned char  TextString392[] ;
 extern const unsigned char  TextString393[] ;
 extern const unsigned char  TextString394[] ;   
 extern const unsigned char  TextString395[] ;
 extern const unsigned char  TextString396[] ;
 extern const unsigned char  TextString397[] ;
 extern const unsigned char  TextString398[] ;
 extern const unsigned char  TextString399[] ;   
 extern const unsigned char  TextString400[] ;
 extern const unsigned char  TextString401[] ;
 extern const unsigned char  TextString400[] ;
 extern const unsigned char  TextString401[] ;
 extern const unsigned char  TextString402[] ;
 extern const unsigned char  TextString403[] ;
 extern const unsigned char  TextString404[] ;
 extern const unsigned char  TextString405[] ;
 extern const unsigned char  TextString406[] ;
 extern const unsigned char  TextString407[] ;
 extern const unsigned char  TextString408[] ;
 extern const unsigned char  TextString409[] ;
 extern const unsigned char  TextString410[] ;
 extern const unsigned char  TextString411[] ;
 extern const unsigned char  TextString412[] ;
 extern const unsigned char  TextString413[] ;
 extern const unsigned char  TextString414[] ;
 extern const unsigned char  TextString415[] ;
 extern const unsigned char  TextString416[] ;
 extern const unsigned char  TextString417[] ;
 extern const unsigned char  TextString418[] ;
 extern const unsigned char  TextString419[] ;
 extern const unsigned char  TextString420[] ;
 extern const unsigned char  TextString421[] ;
 extern const unsigned char  TextString422[] ;
 extern const unsigned char  TextString423[] ;
 extern const unsigned char  TextString424[] ;
 extern const unsigned char  TextString425[] ;
 extern const unsigned char  TextString426[] ;
 extern const unsigned char  TextString427[] ;
 extern const unsigned char  TextString428[] ;
 extern const unsigned char  TextString429[] ;
 extern const unsigned char  TextString430[] ;
 extern const unsigned char  TextString431[] ;
 extern const unsigned char  TextString432[] ;
 extern const unsigned char  TextString433[] ;
 extern const unsigned char  TextString434[] ;
 extern const unsigned char  TextString435[] ;
 extern const unsigned char  TextString436[] ;
 extern const unsigned char  TextString437[] ;
 extern const unsigned char  TextString438[] ;
 extern const unsigned char  TextString439[] ;
 extern const unsigned char  TextString440[] ;
 extern const unsigned char  TextString441[] ;
 extern const unsigned char  TextString442[] ;
 extern const unsigned char  TextString443[] ;
 extern const unsigned char  TextString444[] ;
 extern const unsigned char  TextString445[] ;
 extern const unsigned char  TextString446[] ;
 extern const unsigned char  TextString447[] ;
 extern const unsigned char  TextString448[] ;
 extern const unsigned char  TextString449[] ;
 extern const unsigned char  TextString450[] ;
 extern const unsigned char  TextString451[] ;
 extern const unsigned char  TextString452[] ;
 extern const unsigned char  TextString453[] ;
 extern const unsigned char  TextString454[] ;
 extern const unsigned char  TextString455[] ;
 extern const unsigned char  TextString456[] ;
 extern const unsigned char  TextString457[] ;
 extern const unsigned char  TextString458[] ;
 extern const unsigned char  TextString459[] ;
 extern const unsigned char  TextString460[] ;
 extern const unsigned char  TextString461[] ;
 extern const unsigned char  TextString462[] ;
 extern const unsigned char  TextString463[] ;
 extern const unsigned char  TextString464[] ;
 extern const unsigned char  TextString465[] ;
 extern const unsigned char  TextString466[] ;
 extern const unsigned char  TextString467[] ;
 extern const unsigned char  TextString468[] ;
 extern const unsigned char  TextString469[] ;
 extern const unsigned char  TextString470[] ;
 extern const unsigned char  TextString471[] ;
 extern const unsigned char  TextString472[] ;
 extern const unsigned char  TextString473[] ;
 extern const unsigned char  TextString474[] ;
 extern const unsigned char  TextString475[] ;
 extern const unsigned char  TextString476[] ;
 extern const unsigned char  TextString477[] ;
 extern const unsigned char  TextString478[] ;
 extern const unsigned char  TextString479[] ;
 extern const unsigned char  TextString480[] ;
 extern const unsigned char  TextString481[] ;
 extern const unsigned char  TextString482[] ;
 extern const unsigned char  TextString483[] ;
 extern const unsigned char  TextString484[] ;
 extern const unsigned char  TextString485[] ;
 extern const unsigned char  TextString486[] ;
 extern const unsigned char  TextString487[] ;
 extern const unsigned char  TextString488[] ;
 extern const unsigned char  TextString489[] ;
 extern const unsigned char  TextString490[] ;
 extern const unsigned char  TextString491[] ;
 extern const unsigned char  TextString492[] ;
 extern const unsigned char  TextString493[] ;
 extern const unsigned char  TextString494[] ;
 extern const unsigned char  TextString495[] ;
 extern const unsigned char  TextString496[] ;
 extern const unsigned char  TextString497[] ;
 extern const unsigned char  TextString498[] ;
 extern const unsigned char  TextString499[] ;
 extern const unsigned char  TextString500[] ;
 extern const unsigned char  TextString501[] ;
 extern const unsigned char  TextString502[] ;
 extern const unsigned char  TextString503[] ;
 extern const unsigned char  TextString504[] ;
 extern const unsigned char  TextString505[] ;
 extern const unsigned char  TextString506[] ;
 extern const unsigned char  TextString507[] ;
 extern const unsigned char  TextString508[] ;
 extern const unsigned char  TextString509[] ;
 extern const unsigned char  TextString510[] ;
 extern const unsigned char  TextString511[] ;
 extern const unsigned char  TextString512[] ;
 extern const unsigned char  TextString513[] ;
 extern const unsigned char  TextString514[] ;
 extern const unsigned char  TextString515[] ;
 extern const unsigned char  TextString516[] ;
 extern const unsigned char  TextString517[] ;
 extern const unsigned char  TextString518[] ;
 extern const unsigned char  TextString519[] ;
 extern const unsigned char  TextString520[] ;
 extern const unsigned char  TextString521[] ;
 extern const unsigned char  TextString522[] ;
 extern const unsigned char  TextString523[] ;
 extern const unsigned char  TextString524[] ;
 extern const unsigned char  TextString525[] ;
 extern const unsigned char  TextString526[] ;
 extern const unsigned char  TextString527[] ;
 extern const unsigned char  TextString528[] ;
 extern const unsigned char  TextString529[] ;
 extern const unsigned char  TextString530[] ;
 extern const unsigned char  TextString531[] ;
 extern const unsigned char  TextString532[] ;
 extern const unsigned char  TextString533[] ;
 extern const unsigned char  TextString534[] ;
 extern const unsigned char  TextString535[] ;
 extern const unsigned char  TextString536[] ;
 extern const unsigned char  TextString537[] ;
 extern const unsigned char  TextString538[] ;
 extern const unsigned char  TextString539[] ;
 extern const unsigned char  TextString540[] ;
 extern const unsigned char  TextString541[] ;
 extern const unsigned char  TextString542[] ;
 extern const unsigned char  TextString543[] ;
 extern const unsigned char  TextString544[] ;
 extern const unsigned char  TextString545[] ;
 extern const unsigned char  TextString546[] ;
 extern const unsigned char  TextString547[] ;
 extern const unsigned char  TextString548[] ;
 extern const unsigned char  TextString549[] ;
 extern const unsigned char  TextString550[] ;
 extern const unsigned char  TextString551[] ;
 extern const unsigned char  TextString552[] ;
 extern const unsigned char  TextString553[] ;
 extern const unsigned char  TextString554[] ;
 extern const unsigned char  TextString555[] ;
 extern const unsigned char  TextString556[] ;
 extern const unsigned char  TextString557[] ;
 extern const unsigned char  TextString558[] ;
 extern const unsigned char  TextString559[] ;
 extern const unsigned char  TextString560[] ;
 extern const unsigned char  TextString561[] ;
 extern const unsigned char  TextString562[] ;
 extern const unsigned char  TextString563[] ;
 extern const unsigned char  TextString564[] ;
 extern const unsigned char  TextString565[] ;
 extern const unsigned char  TextString566[] ;
 extern const unsigned char  TextString567[] ;
 extern const unsigned char  TextString568[] ;
 extern const unsigned char  TextString569[] ;
 extern const unsigned char  TextString570[] ;
 extern const unsigned char  TextString571[] ;
 extern const unsigned char  TextString572[] ;
 extern const unsigned char  TextString573[] ;
 extern const unsigned char  TextString574[] ;
 extern const unsigned char  TextString575[] ;
 extern const unsigned char  TextString576[] ;
 extern const unsigned char  TextString577[] ;
 extern const unsigned char  TextString578[] ;
 extern const unsigned char  TextString579[] ;
 extern const unsigned char  TextString580[] ;
 extern const unsigned char  TextString581[] ;
 extern const unsigned char  TextString582[] ;
 extern const unsigned char  TextString583[] ;
 extern const unsigned char  TextString584[] ;
 extern const unsigned char  TextString585[] ;
 extern const unsigned char  TextString586[] ;
 extern const unsigned char  TextString587[] ;
 extern const unsigned char  TextString588[] ;
 extern const unsigned char  TextString589[] ;
 extern const unsigned char  TextString590[] ;
 extern const unsigned char  TextString591[] ;
 extern const unsigned char  TextString592[] ;
 extern const unsigned char  TextString593[] ;
 extern const unsigned char  TextString594[] ;
 extern const unsigned char  TextString595[] ;
 extern const unsigned char  TextString596[] ;
 extern const unsigned char  TextString597[] ;
 extern const unsigned char  TextString598[] ;
 extern const unsigned char  TextString599[] ;
 extern const unsigned char  TextString600[] ;
 extern const unsigned char  TextString601[] ;
 extern const unsigned char  TextString602[] ;
 extern const unsigned char  TextString603[] ;
 extern const unsigned char  TextString604[] ;
 extern const unsigned char  TextString605[] ;
 extern const unsigned char  TextString606[] ;
 extern const unsigned char  TextString607[] ;
 extern const unsigned char  TextString608[] ;
 extern const unsigned char  TextString609[] ;
 extern const unsigned char  TextString610[] ;
 extern const unsigned char  TextString611[] ;
 extern const unsigned char  TextString612[] ;
 extern const unsigned char  TextString613[] ;
 extern const unsigned char  TextString614[] ;
 extern const unsigned char  TextString615[] ;
 extern const unsigned char  TextString616[] ;
 extern const unsigned char  TextString617[] ;
 extern const unsigned char  TextString618[] ;
 extern const unsigned char  TextString619[] ;
 extern const unsigned char  TextString620[] ;
 extern const unsigned char  TextString621[] ;
 extern const unsigned char  TextString622[] ;
 extern const unsigned char  TextString623[] ;
 extern const unsigned char  TextString624[] ;
 extern const unsigned char  TextString625[] ;
 extern const unsigned char  TextString626[] ;
 extern const unsigned char  TextString627[] ;
 extern const unsigned char  TextString628[] ;
 extern const unsigned char  TextString629[] ;
 extern const unsigned char  TextString630[] ;
 extern const unsigned char  TextString631[] ;
 extern const unsigned char  TextString632[] ;
 extern const unsigned char  TextString633[] ;
 extern const unsigned char  TextString634[] ;
 extern const unsigned char  TextString635[] ;
 extern const unsigned char  TextString636[] ;
 extern const unsigned char  TextString637[] ;
 extern const unsigned char  TextString638[] ;
 extern const unsigned char  TextString639[] ;
 extern const unsigned char  TextString640[] ;
 extern const unsigned char  TextString641[] ;
 extern const unsigned char  TextString642[] ;
 extern const unsigned char  TextString643[] ;
 extern const unsigned char  TextString644[] ;
 extern const unsigned char  TextString645[] ;
 extern const unsigned char  TextString646[] ;
 extern const unsigned char  TextString647[] ;
 extern const unsigned char  TextString648[] ;
 extern const unsigned char  TextString649[] ;
 extern const unsigned char  TextString650[] ;
 extern const unsigned char  TextString651[] ;
 extern const unsigned char  TextString652[] ;
 extern const unsigned char  TextString653[] ;
 extern const unsigned char  TextString654[] ;
 extern const unsigned char  TextString655[] ;
 extern const unsigned char  TextString656[] ;
 extern const unsigned char  TextString657[] ; 
 extern const unsigned char  TextString658[] ;
 extern const unsigned char  TextString659[] ;
 extern const unsigned char  TextString660[] ;
 extern const unsigned char  TextString661[] ;
 extern const unsigned char  TextString662[] ;
 extern const unsigned char  TextString663[] ;
 extern const unsigned char  TextString664[] ;
 extern const unsigned char  TextString665[] ;
 extern const unsigned char  TextString666[] ;
 extern const unsigned char  TextString667[] ;
 extern const unsigned char  TextString668[] ;
 extern const unsigned char  TextString669[] ;
 extern const unsigned char  TextString670[] ;
 extern const unsigned char  TextString671[] ;
 

  extern const unsigned char  TextStringEvent1001[];
  extern const unsigned char  TextStringEvent1002[];
  extern const unsigned char  TextStringEvent1003[];
  extern const unsigned char  TextStringEvent1004[];
  extern const unsigned char  TextStringEvent1005[];
  extern const unsigned char  TextStringEvent1006[];
 extern  const unsigned char  TextStringEvent1007[];
  extern const unsigned char  TextStringEvent1008[];
  extern const unsigned char  TextStringEvent1009[];
  extern const unsigned char  TextStringEvent1010[];
  extern const unsigned char  TextStringEvent1011[];
  extern const unsigned char  TextStringEvent1012[];
  extern const unsigned char  TextStringEvent1013[];
  extern const unsigned char  TextStringEvent1014[];
  extern const unsigned char  TextStringEvent1015[];
  extern const unsigned char  TextStringEvent1016[];
  extern const unsigned char  TextStringEvent1032[];
  extern const unsigned char  TextStringEvent1033[];
  extern const unsigned char  TextStringEvent1034[];
  extern const unsigned char  TextStringEvent1035[];
  extern const unsigned char  TextStringEvent1036[];
  extern const unsigned char  TextStringEvent1041[];
  extern const unsigned char  TextStringEvent1051[];
  extern const unsigned char  TextStringEvent1052[];
  extern const unsigned char  TextStringEvent1053[];
  extern const unsigned char  TextStringEvent1054[];
  extern const unsigned char  TextStringEvent1055[];
  extern const unsigned char  TextStringEvent1071[];
  extern const unsigned char  TextStringEvent1073[];
  extern const unsigned char  TextStringEvent1074[];
  extern const unsigned char  TextStringEvent1075[];
  extern const unsigned char  TextStringEvent1101[];
  extern const unsigned char  TextStringEvent1102[];
  extern const unsigned char  TextStringEvent1103[];
  extern const unsigned char  TextStringEvent1104[];
  extern const unsigned char  TextStringEvent1105[];
  extern const unsigned char  TextStringEvent1106[];
  extern const unsigned char  TextStringEvent1107[];
  extern const unsigned char  TextStringEvent1108[];
  extern const unsigned char  TextStringEvent1109[];
  extern const unsigned char  TextStringEvent1110[];
  extern const unsigned char  TextStringEvent1111[];
  extern const unsigned char  TextStringEvent1112[];
  extern const unsigned char  TextStringEvent1113[];
  extern const unsigned char  TextStringEvent1114[];
  extern const unsigned char  TextStringEvent1120[];
  extern const unsigned char  TextStringEvent1121[];
  extern const unsigned char  TextStringEvent1122[];
  extern const unsigned char  TextStringEvent1123[];
  extern  const unsigned char  TextStringEvent1124[];
  extern const unsigned char  TextStringEvent1125[];
  extern const unsigned char  TextStringEvent1126[];
  extern const unsigned char  TextStringEvent1127[];
  extern const unsigned char  TextStringEvent1128[];
  extern const unsigned char  TextStringEvent1129[];
  extern const unsigned char  TextStringEvent1130[];
  extern const unsigned char  TextStringEvent1131[];
  extern const unsigned char  TextStringEvent1132[];
  extern const unsigned char  TextStringEvent1133[];
  extern const unsigned char  TextStringEvent1134[];
  extern const unsigned char  TextStringEvent1135[];
  extern const unsigned char  TextStringEvent1136[];
  extern const unsigned char  TextStringEvent1137[];
  extern const unsigned char  TextStringEvent1138[];
  extern const unsigned char  TextStringEvent1139[];
  extern const unsigned char  TextStringEvent1140[];
  extern const unsigned char  TextStringEvent1141[];
  extern const unsigned char  TextStringEvent1142[];
  extern const unsigned char  TextStringEvent1143[];
  extern const unsigned char  TextStringEvent1144[];
  extern const unsigned char  TextStringEvent1145[];
  extern const unsigned char  TextStringEvent1146[];
  extern const unsigned char  TextStringEvent1147[];
  extern const unsigned char  TextStringEvent1148[];
  extern const unsigned char  TextStringEvent1149[];
  extern const unsigned char  TextStringEvent1150[];
  extern const unsigned char  TextStringEvent1151[];
  extern const unsigned char  TextStringEvent1152[];
  extern const unsigned char  TextStringEvent1153[];
  extern const unsigned char  TextStringEvent1154[];
  extern const unsigned char  TextStringEvent1155[];
  extern const unsigned char  TextStringEvent1156[];
  extern const unsigned char  TextStringEvent1157[];
  extern const unsigned char  TextStringEvent1158[];
  extern const unsigned char  TextStringEvent1159[];
  extern const unsigned char  TextStringEvent1170[];
  extern const unsigned char  TextStringEvent1180[];
  extern const unsigned char  TextStringEvent1181[];
  extern const unsigned char  TextStringEvent1182[];
  extern const unsigned char  TextStringEvent1183[];
  extern const unsigned char  TextStringEvent1184[];
  extern const unsigned char  TextStringEvent1185[];
  extern const unsigned char  TextStringEvent1186[];

 
 
 
 
           
extern const unsigned char  PunctuationMark1[];
extern const unsigned char  PunctuationMark2[];
extern const unsigned char  PunctuationMark3[];
extern const unsigned char  PunctuationMark4[];
extern const unsigned char  PunctuationMark5[];
extern const unsigned char  PunctuationMark6[];
extern const unsigned char  PunctuationMark7[];
extern const unsigned char  PunctuationMark8[];
extern const unsigned char  PunctuationMark9[];
extern const unsigned char  PunctuationMark10[];
extern const unsigned char  PunctuationMark11[];
extern const unsigned char  PunctuationMark12[];
extern const unsigned char  PunctuationMark13[];
extern const unsigned char  PunctuationMark14[];
extern const unsigned char  PunctuationMark15[];
extern const unsigned char  PunctuationMark16[];
extern const unsigned char  PunctuationMark17[];
extern const unsigned char  PunctuationMark18[];
extern const unsigned char  PunctuationMark19[];
extern const unsigned char  PunctuationMark20[];
extern const unsigned char  PunctuationMark21[];
extern const unsigned char  PunctuationMark22[];
extern const unsigned char  PunctuationMark23[];
extern const unsigned char  PunctuationMark24[];
extern const unsigned char  PunctuationMark25[];
extern const unsigned char  PunctuationMark26[];
extern const unsigned char  PunctuationMark27[];
extern const unsigned char  PunctuationMark28[];

#endif 