/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Func_for_GUI_Public.h"


extern WM_HWIN Create_Framewin_Polling_Device_Menu_in_Slave_Single ( void );



WM_HWIN CreateFramewinMenuDeviceList ( void )                  ; 


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x01)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, (const char *)&TextString240, ID_FRAMEWIN_0, 25, 25, 775, 455, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect,  NULL, ID_LISTBOX_0, 0, 0, 775, 418, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //    
   hItem = pMsg->hWin;
   FRAMEWIN_SetTitleHeight(hItem, 37);
   FRAMEWIN_SetBarColor(hItem,0, GUI_RED);
   FRAMEWIN_SetFont(hItem, &GUI_FontVerdana35);
   FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER);     
    //
    // Initialization of 'Listbox'
    //
   hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
   LISTBOX_EnableWrapMode(hItem, 1);
   LISTBOX_SetFont(hItem, &GUI_FontVerdana35);
   LISTBOX_SetAutoScrollV(hItem, 1);
   LISTBOX_SetTextAlign(hItem, GUI_TA_LEFT);
   LISTBOX_SetBkColor(hItem, LISTBOX_CI_SELFOCUS, 0xFFBF00);
   LISTBOX_SetBkColor(hItem, LISTBOX_CI_UNSEL,    0xFAE6E6);
   LISTBOX_AddString(hItem, (const char *)&TextString28);//ÒÀÁËÈÖÀ ÓÑÒÐÎÉÑÒÂ                0     
 
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
    case WM_KEY:    
                 switch (pMsg->Data.v)
                    {        
                      case GUI_KEY_ENTER_HAND :  
                                                  switch  (LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)))
                                                         {
                                                          case 0:    Create_Framewin_Polling_Device_Menu_in_Slave_Single ( ); //ïåðâûé ïóíêò ìåíþ 
                                                                     break ;                                                                                                                  
                                                          case 1:   
                                                                     break ;                                                      
                                                          case 2:                                                                                                                            
                                                                     break ;       
                                                          case 3:                                                                                                                                    
                                                                     break ;                
                                                          case 4:                                                                                                                                
                                                                     break ;      
                                                                         
                                                          default : break ;            
                                                         }                                                                                         
                                               break ; 
                      case GUI_KEY_UP_HAND:     LISTBOX_DecSel (WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));  break ;                                                                                        
                      case GUI_KEY_DOWN_HAND:   LISTBOX_IncSel (WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));  break ; 
                      case GUI_KEY_F3_HAND  :   break ;                                                                                  
                      case GUI_KEY_F2_HAND  :   break ; 
                      case GUI_KEY_F1_HAND  :   break ; 
                      case GUI_KEY_ESCAPE_HAND: GUI_EndDialog(pMsg->hWin,1)           ;       
                                                break ;
                      default : break ;  
                    }
                 break ; 
   case WM_PRE_PAINT:  
                      if(!Cheak_Focus_Windows(WM_GetClientWindow(pMsg->hWin)))
                      {
                        if(Cheak_Cover_Windows_2(WM_GetClientWindow(pMsg->hWin)) )
                        {
                          WM_SetFocus(pMsg->hWin) ;   
                        }
                      }
                      break ;                   
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
      default : break ;   
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       
*/
WM_HWIN CreateFramewinMenuDeviceList ( void ) 
{
  WM_HWIN hWin;

  if(Check_GUI_RAM())
  {
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  }
  return hWin;
}
// USER START (Optionally insert additional public code)
// USER END
/*************************** End of file ****************************/
