/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END


#include "Main_Menu_Icon.h"
#include "Func_for_GUI_Public.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 1)
#define ID_EDIT_0       (GUI_ID_USER + 2)
#define ID_TEXT_1       (GUI_ID_USER + 3)
#define ID_TEXT_2       (GUI_ID_USER + 4)
#define ID_TEXT_3       (GUI_ID_USER + 5)
#define ID_TEXT_4       (GUI_ID_USER + 6)
#define ID_TEXT_5       (GUI_ID_USER + 7)
#define ID_TIMER_TIMER  (GUI_ID_USER + 8)

WM_HWIN CreateFramewinMenuDeviceList ( void )                                   ;
WM_HWIN CreateWindowIconFirstMenu    ( void )                                   ;


extern WM_HWIN CreateFramewinEventLog ( void ) ;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static uint8_t sost =   0;
static uint8_t direct = 0;
static uint8_t cursor = 0;

const uint16_t KTH=25 ;

const uint16_t SizeIconX=89 ;
const uint16_t SizeIconY=89 ;

const uint16_t IconToolsX=36 ;
const uint16_t IconToolsY=35 ;

const uint16_t IconBufAlarmX=426 ;
const uint16_t IconBufAlarmY=150 ;

const uint16_t IconJourX=36 ;
const uint16_t IconJourY=150 ;

const uint16_t IconAcpX=36 ;
const uint16_t IconAcpY=265 ;

const uint16_t IconControlX=426 ;
const uint16_t IconControlY=35 ;
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
{ FRAMEWIN_CreateIndirect,(const char *)&TextString241,   ID_FRAMEWIN_0, 25, 25, 775, 455, 0, 0x0, 0 },
{ EDIT_CreateIndirect,                        NULL, ID_EDIT_0,     100, 550,  80, 20,  0, 0x64, 0 },
{ TEXT_CreateIndirect,(const char *)&TextString1,   ID_TEXT_1, 150, 70, 110, 45, 0, 0x0, 0 },         // настройка        
{ TEXT_CreateIndirect,(const char *)&TextString2,   ID_TEXT_2, 150, 185, 170, 45, 0, 0x0, 0 },        // журнал
{ TEXT_CreateIndirect,(const char *)&TextString240, ID_TEXT_3,  543, 70, 220, 45, 0, 0x0, 0 },        //управление
{ TEXT_CreateIndirect,(const char *)&TextString62, ID_TEXT_4, 543, 185, 222, 45, 0, 0x0, 0 },         //"Буфер тревог"
{ TEXT_CreateIndirect,(const char *)&TextString460, ID_TEXT_5, 150, 300, 155, 45, 0, 0x0, 0},         //"Подтверждения"
  // USER START (Optionally insert additional widgets)
  // USER END"Подтверждения"
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static WM_HMEM GiuTim = 0 ;
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem; 

  int     NCode;
  int     Id;
 
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) 
  {
     case WM_TIMER: if (WM_GetTimerId(pMsg->Data.v) == ID_TIMER_TIMER)
	            { 
                   //   if(Get_Block() )
                      if (1)
                     { 
 		       if (sost >= 10)
		       {
		 	direct = 1;	
		       }
		       else  if (sost <= 1)
		       {
		  	direct = 0;
		       } 

	               if (direct)
	               {
		  	 sost--;
	               }
		       else
		       {
		  	 sost++;
		       }
		       if (sost > 10)
		       {
		 	 sost = 10;
		       }
		     WM_InvalidateWindow(WM_GetClientWindow(pMsg->hWin));
                     }
	  	      WM_RestartTimer(pMsg->Data.v, 150);
	            }
                   
		    break;
     case WM_INIT_DIALOG:    
	hItem = pMsg->hWin;    
        
     //   hItem =WM_GetClientWindow(pMsg.hWin);  //Настройки
	FRAMEWIN_SetTitleHeight(hItem, 37);
 //      FRAMEWIN_SetActive     (hItem, 1);
  //     FRAMEWIN_SetActive     (hItem, 2);
//        FRAMEWIN_SetBarColor   (hItem,1, GUI_RED);      
        //FRAMEWIN_SetActive     (hItem, ID_FRAMEWIN_0), 1);
  //      FRAMEWIN_SetBarColor   (hItem,0, GUI_RED);   
    //    FRAMEWIN_SetTextColor(hItem, GUI_WHITE);
        
	FRAMEWIN_SetFont(hItem, &GUI_FontVerdana35);
	FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER);
        
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);  //Настройки
	TEXT_SetFont(hItem, &GUI_FontVerdana23);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);  //Подтверждения
	TEXT_SetFont(hItem, &GUI_FontVerdana23);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);  //Управление
	TEXT_SetFont(hItem, &GUI_FontVerdana23);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);  //Журнал
	TEXT_SetFont(hItem, &GUI_FontVerdana23);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);  //Буфер тревог
	TEXT_SetFont(hItem, &GUI_FontVerdana23);
         
     //   GiuTim = WM_CreateTimer( WM_GetClientWindow ( pMsg.hWin ) , ID_TIMER_TIMER , 500, 0 ) ;  
       //  WM_SetCallback(WM_GetClientWindow(pMsg.hWin), _cbBk1); 
          WM_SetFocus(pMsg->hWin) ; 
         break ;
    
   case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0 : // Notifications sent by 'OK'
      switch(NCode)
      {
        case WM_NOTIFICATION_CLICKED:
          // USER START (Optionally insert code for reacting on notification message)
          // USER END
          break;
        case WM_NOTIFICATION_RELEASED:
          // USER START (Optionally insert code for reacting on notification message)
          // USER END
          break;
         case WM_NOTIFICATION_GOT_FOCUS :
                  if ( !GiuTim )
                  {
                 //    GiuTim = WM_CreateTimer( WM_GetClientWindow ( pMsg.hWin ) , ID_TIMER_TIMER , 500, 0 ) ;  
                  }
          break ;  
          case WM_NOTIFICATION_LOST_FOCUS :
                 if ( GiuTim )
                 {
                   // WM_DeleteTimer( GiuTim ) ;  
                    GiuTim = 0 ; 
                 }
          break ;  
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
       }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
      
     case WM_KEY:   
                        switch (pMsg->Data.v)
                        {                 
                           case GUI_KEY_F2_HAND   :         break ;             
                           case GUI_KEY_F3_HAND   :         break ;               
                           case GUI_KEY_F1_HAND   :         break  ; 
                           case GUI_KEY_LEFT_HAND: 
                                                   if(cursor)
                                                   {
                                                     cursor-- ;
                                                   }
                                                   else
                                                   {
                                                    cursor=4 ;
                                                   }
                                                   sost=0 ;   
                                                   WM_InvalidateWindow(WM_GetClientWindow(pMsg->hWin));
                                                   break ;    
                           case GUI_KEY_UP_HAND:   if(cursor>=2)
                                                   {
                                                     cursor-=2 ;
                                                   }   
                                                   else
                                                   {
                                                     cursor=4 ;
                                                   }
                                                   WM_InvalidateWindow(WM_GetClientWindow(pMsg->hWin));
                                                   break ;                                                   
                           case GUI_KEY_DOWN_HAND: cursor+=2 ;
                                                   if(cursor>4)
                                                   {
                                                     cursor=0 ;
                                                   }
                                                   sost=0 ;   
                                                   WM_InvalidateWindow(WM_GetClientWindow(pMsg->hWin));
                                                   break ;                                                               
                           case GUI_KEY_RIGHT_HAND:cursor++ ;
                                                   if(cursor>4)
                                                   {
                                                     cursor=0 ;
                                                   }
                                                   sost=0 ; 
                                                   WM_InvalidateWindow(WM_GetClientWindow(pMsg->hWin));
                                                   break ;  
                           case GUI_KEY_ZERO_HAND: break ;
                           case GUI_KEY_ONE_HAND:  break  ; 
                           case GUI_KEY_TWO_HAND:  /*HAL_FLASH_Unlock();
                                                   EraseInitStruct.TypeErase = FLASH_TYPEERASE_SECTORS;
                                                   EraseInitStruct.VoltageRange = FLASH_VOLTAGE_RANGE_3;
                                                   EraseInitStruct.Sector = 7;
                                                   EraseInitStruct.NbSectors = 1;
                                                   if(HAL_FLASHEx_Erase(&EraseInitStruct, &SectorError) != HAL_OK)
                                                   {                                             
                                                      Error_Handler () ; 
                                                   }  
                                                   HAL_FLASH_Lock();*/ 
                                                   break ; 
                       case GUI_KEY_THREE_HAND :   break ;  
                       case GUI_KEY_FOUR_HAND  :   break ;                      
                       case GUI_KEY_FIVE_HAND  :   break ;
                       case GUI_KEY_SIX_HAND   :   break ;                    
                       case GUI_KEY_SEVEN_HAND :   break ;                    
                       case GUI_KEY_EIGHT_HAND :   break ;                                           
                       case GUI_KEY_NINE_HAND  :   break ;                           
                       case GUI_KEY_ENTER_HAND :  
                                                      switch (cursor)
                                                      {
                                                         case 0: break ;   
                                                         case 1: CreateFramewinMenuDeviceList () ; 
                                                                 break ; 
                                                         case 2: CreateFramewinEventLog();break;        
                                                         case 3: break ;
                                                         default : break ;
                                                      }        
                                                                                                             
                                                   break ;                  
                           case GUI_KEY_ESCAPE_HAND:   break ;   
                           default: break ;
                        }                             
                        break ; 
    case WM_PRE_PAINT:  
                      if(!Cheak_Focus_Windows(WM_GetClientWindow(pMsg->hWin)))
                      {
                        if(Cheak_Cover_Windows_2(WM_GetClientWindow(pMsg->hWin)) )
                        {
                          WM_SetFocus(pMsg->hWin) ;   
                        }
                      } 
                      break ;    
   case WM_PAINT:          
        
           GUI_DrawGradientV(0, 0, 800, 480, 0xFAE6E6, 0xEBCE87) ; 
     
           GUI_SetTextMode(GUI_TM_TRANS);
           GUI_SetColor(GUI_BLACK);
       
	   GUI_DrawGradientRoundedH(18, 28, 352, 131, 5,  GUI_RED, GUI_RED); //1
	   GUI_DrawGradientRoundedH(408, 28, 742, 131, 5, GUI_RED, GUI_RED); //2
	   GUI_DrawGradientRoundedH(18, 143, 352, 246, 5, GUI_RED, GUI_RED); //3
	   GUI_DrawGradientRoundedH(408, 143, 742, 246, 5,GUI_RED, GUI_RED); //4
           GUI_DrawGradientRoundedH(18, 258, 352, 361, 5, GUI_RED, GUI_RED); //5
	
	   GUI_DrawGradientRoundedH(20, 30, 350, 129,5,   0xFFBF00,0xED9564); //1
	   GUI_DrawGradientRoundedH(410, 30, 740, 129, 5, 0xFFBF00, 0xED9564); //2
	   GUI_DrawGradientRoundedH(20, 145, 350, 244, 5, 0xFFBF00, 0xED9564);//3
	   GUI_DrawGradientRoundedH(410, 145, 740, 244, 5,0xFFBF00, 0xED9564); //4       
	   GUI_DrawGradientRoundedH(20, 260, 350, 359, 5, 0xFFBF00, 0xED9564); //5    
            
         
             switch (cursor)
             {
               case 0:  GUI_DrawGradientRoundedH(20, 30, 350, 129,5,   0x7FE9FF,0x7FE9FF);  break ;
               case 1:  GUI_DrawGradientRoundedH(410, 30, 740, 129, 5, 0x7FE9FF, 0x7FE9FF); break ;
               case 2:  GUI_DrawGradientRoundedH(20, 145, 350, 244, 5, 0x7FE9FF, 0x7FE9FF); break ;
               case 3:  GUI_DrawGradientRoundedH(410, 145, 740, 244, 5,0x7FE9FF, 0x7FE9FF); break ;
               case 4:  GUI_DrawGradientRoundedH(20, 260, 350, 359, 5, 0x7FE9FF, 0x7FE9FF); break ;
               default: break ;
             }

                    
	   //0 иконка
	   GUI_DrawGradientRoundedH(IconToolsX, IconToolsY,(SizeIconX+IconToolsX), (SizeIconY+IconToolsY), 6, 0x446EE9, 0x446EE9);
	   GUI_SetColor(0x2444B5);
	   GUI_FillPolygon(IconToolsShadow, GUI_COUNTOF(IconToolsShadow), IconToolsX, IconToolsY);
	   GUI_SetColor(GUI_WHITE);

	   GUI_DrawPolygon(IconTools1,       GUI_COUNTOF(IconTools1), IconToolsX, IconToolsY);
	   GUI_DrawPolygon(IconTools2,       GUI_COUNTOF(IconTools2), IconToolsX, IconToolsY);
	   GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
	   GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
	   GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF( IconToolsCircle3), IconToolsX, IconToolsY);
           
           if(cursor!=0 ) //|| !Get_Block())
           {
             GUI_DrawPolygon(IconToolsGear8, GUI_COUNTOF(IconToolsGear8), IconToolsX, IconToolsY);
	     GUI_DrawPolygon(IconToolsRing1, GUI_COUNTOF(IconToolsRing1), IconToolsX, IconToolsY);				
	     GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);				
	     GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
	     GUI_SetColor(GUI_WHITE);
	     GUI_FillPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
           }          
	   //1 иконка                     
	   GUI_DrawGradientRoundedH(IconControlX, IconControlY, (SizeIconX+IconControlX) , (SizeIconY+IconControlY) , 6, 0x1AB1FB, 0x1AB1FB);
	   GUI_SetColor(0x1697D6);
	   GUI_FillPolygon(IconControlShadow, GUI_COUNTOF(IconControlShadow), IconControlX, IconControlY);
           GUI_SetColor(GUI_WHITE);
		
	   GUI_DrawPolygon(IconControlLine1, GUI_COUNTOF(IconControlLine1), IconControlX, IconControlY);
	   GUI_DrawPolygon(IconControlLine2, GUI_COUNTOF(IconControlLine2), IconControlX, IconControlY);
           GUI_DrawPolygon(IconControlLine3, GUI_COUNTOF(IconControlLine3), IconControlX, IconControlY);
	   GUI_DrawPolygon(IconControlLine4, GUI_COUNTOF(IconControlLine4), IconControlX, IconControlY);

           if(cursor!=1)
           {
             GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX + (42-KTH),IconControlY +(63-KTH));
	     GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(61-KTH));
	     GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(73-KTH));
	     GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(51-KTH));
             GUI_SetColor(0x1697D6);
	     GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(63-KTH));
             GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(61-KTH));
	     GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(73-KTH));
	     GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(51-KTH));
           }
	   //2 иконка 
           GUI_DrawGradientRoundedH(36, 150, 124, 239, 6, 0xC69E2E, 0xC69E2E);
           GUI_SetColor(0xA88726);
	   GUI_FillPolygon(IconJurnalShadow, GUI_COUNTOF(IconJurnalShadow), IconJourX, IconJourY);
	   GUI_SetColor(GUI_WHITE);
           if(cursor!=2)
           {
             GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText6, GUI_COUNTOF(IconJurnalText6), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText7, GUI_COUNTOF(IconJurnalText7), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText8, GUI_COUNTOF(IconJurnalText8), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalText9, GUI_COUNTOF(IconJurnalText9), IconJourX, IconJourY);
             
             GUI_SetColor(GUI_WHITE);
	     GUI_DrawPolygon(IconJurnalPage2, GUI_COUNTOF(IconJurnalPage2), IconJourX, IconJourY);
	     GUI_DrawPolygon(IconJurnalPage1, GUI_COUNTOF(IconJurnalPage1), IconJourX, IconJourY);	
           }
           
	   //3 иконка
	   GUI_DrawGradientRoundedH(IconBufAlarmX,IconBufAlarmY,(SizeIconX+IconBufAlarmX) ,(SizeIconY+IconBufAlarmY) , 6, 0x1AB1FB, 0x1AB1FB);
	   GUI_SetColor(0x1697D6);
	   GUI_FillPolygon(IconBufferShadow, GUI_COUNTOF(IconBufferShadow), IconBufAlarmX, IconBufAlarmY);
	   GUI_SetColor(GUI_WHITE);
	   GUI_DrawPolygon(IconBufferBox, GUI_COUNTOF(IconBufferBox), IconBufAlarmX, IconBufAlarmY);
            
           if(cursor!=3)
           {
             GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
	     GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
	     GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
             GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);	
           }
           
           //4 иконка                  
	   GUI_DrawGradientRoundedH(IconAcpX, IconAcpY, (IconAcpX+SizeIconX) ,(IconAcpY+SizeIconY),6, 0x446EE9, 0x446EE9);
           GUI_SetColor(0x395EC6);
           GUI_FillPolygon(IconAcceptShadow, GUI_COUNTOF(IconAcceptShadow), IconAcpX, IconAcpY);
	   GUI_SetColor(GUI_WHITE);
           if(cursor!=4)
           {
              GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
	      GUI_SetColor(0x395EC6);
	      GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);
	      GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
	      GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
              GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
	      GUI_SetColor(GUI_WHITE);
	      GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
	      GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
	      GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
	      GUI_SetColor(0x395EC6);
	      GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
	      GUI_SetColor(GUI_WHITE);
	      GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
	      GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);
              
              GUI_SetColor(GUI_WHITE);
	      GUI_DrawPolygon(IconAcceptHand, GUI_COUNTOF(IconAcceptHand), IconAcpX, IconAcpY);
           } 
       //    if(!Get_Block())
       //    {
       //      break ;
       //    }
            
           switch (cursor)
	   {
             case 0:
               switch (sost)
			{
			case 0:
				GUI_DrawPolygon(IconToolsGear8, GUI_COUNTOF(IconToolsGear8), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsRing1, GUI_COUNTOF(IconToolsRing1), IconToolsX, IconToolsY);				
				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);				
				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 1:	GUI_DrawPolygon(IconToolsGear9, GUI_COUNTOF(IconToolsGear9), IconToolsX, IconToolsY-1);
				GUI_DrawPolygon(IconToolsRing2, GUI_COUNTOF(IconToolsRing2), IconToolsX, IconToolsY-1);
				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);

				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 2:	GUI_DrawPolygon(IconToolsGear10, GUI_COUNTOF(IconToolsGear10), IconToolsX, IconToolsY-2);
				GUI_DrawPolygon(IconToolsRing3, GUI_COUNTOF(IconToolsRing3), IconToolsX, IconToolsY-2);
				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);

				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 3:	GUI_DrawPolygon(IconToolsGear11, GUI_COUNTOF(IconToolsGear11), IconToolsX, IconToolsY-3);
				GUI_DrawPolygon(IconToolsRing4, GUI_COUNTOF(IconToolsRing4), IconToolsX, IconToolsY-3);

				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
                                GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);				
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 4:	GUI_DrawPolygon(IconToolsGear12, GUI_COUNTOF(IconToolsGear12), IconToolsX, IconToolsY-4);
				GUI_DrawPolygon(IconToolsRing5, GUI_COUNTOF(IconToolsRing5), IconToolsX, IconToolsY-4);

				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 5:	GUI_DrawPolygon(IconToolsGear13, GUI_COUNTOF(IconToolsGear13), IconToolsX, IconToolsY-5);
				GUI_DrawPolygon(IconToolsRing6, GUI_COUNTOF(IconToolsRing6), IconToolsX, IconToolsY-5);

				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 6:	GUI_DrawPolygon(IconToolsGear14, GUI_COUNTOF(IconToolsGear14), IconToolsX, IconToolsY-6);
				GUI_DrawPolygon(IconToolsRing7, GUI_COUNTOF(IconToolsRing7), IconToolsX, IconToolsY-6);

				GUI_DrawPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 7:	GUI_DrawPolygon(IconToolsGear15, GUI_COUNTOF(IconToolsGear15), IconToolsX, IconToolsY-7);
				GUI_DrawPolygon(IconToolsRing8, GUI_COUNTOF(IconToolsRing8), IconToolsX, IconToolsY-7);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
				
				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 8:	GUI_DrawPolygon(IconToolsGear16, GUI_COUNTOF(IconToolsGear16), IconToolsX, IconToolsY-8);
				GUI_DrawPolygon(IconToolsRing9, GUI_COUNTOF(IconToolsRing9), IconToolsX, IconToolsY-8);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);

				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 9:	GUI_DrawPolygon(IconToolsGear17, GUI_COUNTOF(IconToolsGear17), IconToolsX, IconToolsY-9);
				GUI_DrawPolygon(IconToolsRing10, GUI_COUNTOF(IconToolsRing10), IconToolsX, IconToolsY-9);
				GUI_SetColor(GUI_WHITE);
				GUI_FillPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);

				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
			case 10:GUI_DrawPolygon(IconToolsGear18, GUI_COUNTOF(IconToolsGear18), IconToolsX, IconToolsY-10);
				GUI_DrawPolygon(IconToolsRing11, GUI_COUNTOF(IconToolsRing11), IconToolsX, IconToolsY-10);
				GUI_SetColor(GUI_WHITE);
                                
				GUI_FillPolygon(IconToolsCircle1, GUI_COUNTOF(IconToolsCircle1), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle2, GUI_COUNTOF(IconToolsCircle2), IconToolsX, IconToolsY);
				GUI_DrawPolygon(IconToolsCircle3, GUI_COUNTOF(IconToolsCircle3), IconToolsX, IconToolsY);
				break;
                        default : break ;       
			}
                      break ;
              ///////////////////////////////////////////////////
              case 1:             
			switch (sost)
			{
			case 0:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX + (42-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(73-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(51-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(73-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(51-KTH));
				break;
			case 1:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(62-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(62-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(71-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(54-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(62-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(62-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(71-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(54-KTH));
				break;
			case 2:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(69-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(57-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(69-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(57-KTH));
				break;
			case 3:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(60-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(64-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY+ (67-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(60-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(60-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(64-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(67-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(60-KTH));
				break;
			case 4:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(59-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(65-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(65-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(63-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(59-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(65-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(65-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(63-KTH));
				break;
			case 5:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY+ (58-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY+ (66-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(66-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(58-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(66-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(63-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(66-KTH));
				break;
			case 6:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(57-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(67-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(69-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY+ (57-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(67-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(61-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(69-KTH));
				break;
			case 7:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY+ (56-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY+ (68-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(59-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(72-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY+ (56-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY+ (68-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY+ (59-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(72-KTH));
				break;
			case 8:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(55-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(69-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(57-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(75-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(55-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY+ (69-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY+ (57-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(75-KTH));
				break;
			case 9:	GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(54-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY+ (70-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(55-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(78-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(54-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY+ (70-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(55-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(78-KTH));
				break;
			case 10:GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(42-KTH),IconControlY +(53-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(57-KTH),IconControlY +(71-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(72-KTH),IconControlY +(53-KTH));
				GUI_FillPolygon(IconControlCircle1, GUI_COUNTOF(IconControlCircle1),IconControlX +(87-KTH),IconControlY +(81-KTH));
				GUI_SetColor(0x1697D6);
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(42-KTH),IconControlY +(53-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(57-KTH),IconControlY +(71-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(72-KTH),IconControlY +(53-KTH));
				GUI_FillPolygon(IconControlCircle2, GUI_COUNTOF(IconControlCircle2),IconControlX +(87-KTH),IconControlY +(81-KTH));
				break;
                        default : break ;       
		     }
                     break ;  
              ///////////////////////////////////////////////////  
             case 2: { 
			switch (sost)
			{
			case 0:	break;
			case 1:	break;
			case 2:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				break;
			case 3:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);															
				break;
			case 4:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);			
				break;
			case 5:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				break;
			case 6:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
				break;
			case 7:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText6, GUI_COUNTOF(IconJurnalText6), IconJourX, IconJourY);
				break;
			case 8:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText6, GUI_COUNTOF(IconJurnalText6), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText7, GUI_COUNTOF(IconJurnalText7), IconJourX, IconJourY);
				break;
			case 9:	GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText6, GUI_COUNTOF(IconJurnalText6), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText7, GUI_COUNTOF(IconJurnalText7), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText8, GUI_COUNTOF(IconJurnalText8), IconJourX, IconJourY);
				break;
			case 10:GUI_DrawPolygon(IconJurnalText1, GUI_COUNTOF(IconJurnalText1), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText2, GUI_COUNTOF(IconJurnalText2), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText3, GUI_COUNTOF(IconJurnalText3), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText4, GUI_COUNTOF(IconJurnalText4), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText5, GUI_COUNTOF(IconJurnalText5), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText6, GUI_COUNTOF(IconJurnalText6), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText7, GUI_COUNTOF(IconJurnalText7), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText8, GUI_COUNTOF(IconJurnalText8), IconJourX, IconJourY);
				GUI_DrawPolygon(IconJurnalText9, GUI_COUNTOF(IconJurnalText9), IconJourX, IconJourY);					
				break;
                        default : break ;       
			}					
			GUI_SetColor(GUI_WHITE);
			GUI_DrawPolygon(IconJurnalPage2, GUI_COUNTOF(IconJurnalPage2), IconJourX, IconJourY);
			GUI_DrawPolygon(IconJurnalPage1, GUI_COUNTOF(IconJurnalPage1), IconJourX, IconJourY);				  
                        break ;                      
              }         
             ///////////////////////////////////////////////////  
             case 3: { 
			switch (sost)
			{
			case 0:	break;
			case 1:	break;
			case 2:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				break;
			case 3:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);			
				break;
			case 4:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				break;
			case 5:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);			
				break;
			case 6:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);
				break;
			case 7:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);
				break;
			case 8:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);
				break;
			case 9:	GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);
				break;
			case 10:GUI_DrawPolygon(IconBufferTextline1, GUI_COUNTOF(IconBufferTextline1), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline2, GUI_COUNTOF(IconBufferTextline2), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline3, GUI_COUNTOF(IconBufferTextline3), IconBufAlarmX, IconBufAlarmY);
				GUI_DrawPolygon(IconBufferTextline4, GUI_COUNTOF(IconBufferTextline4), IconBufAlarmX, IconBufAlarmY);
				sost=0 ; 
				break;
                        default:break ;       
			}
                     break ;   
                     
              }
            ///////////////////////////////////////////////////  
             case 4: { 
			switch (sost)
			{
			case 0:	GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				break;
			case 1:	GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				break;
			case 2:	GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);			
				break;
			case 3:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);			
				break;
			case 4:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);			
				break;
			case 5:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);			
				break;
			case 6:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);				
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);
				break;
			case 7:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);				
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);
				break;
			case 8:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);				
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);
				break;
			case 9:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);				
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);
				break;
			case 10:
				GUI_DrawPolygon(IconAcceptLine1, GUI_COUNTOF(IconAcceptLine1), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine2Shadow, GUI_COUNTOF(IconAcceptLine2Shadow), IconAcpX, IconAcpY);				
				GUI_FillPolygon(IconAcceptLine3Shadow, GUI_COUNTOF(IconAcceptLine3Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine4Shadow, GUI_COUNTOF(IconAcceptLine4Shadow), IconAcpX, IconAcpY);
				GUI_FillPolygon(IconAcceptLine5Shadow, GUI_COUNTOF(IconAcceptLine5Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine3, GUI_COUNTOF(IconAcceptLine3), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine4, GUI_COUNTOF(IconAcceptLine4), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine5, GUI_COUNTOF(IconAcceptLine5), IconAcpX, IconAcpY);
				GUI_SetColor(0x395EC6);
				GUI_FillPolygon(IconAcceptLine6Shadow, GUI_COUNTOF(IconAcceptLine6Shadow), IconAcpX, IconAcpY);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawPolygon(IconAcceptLine2, GUI_COUNTOF(IconAcceptLine2), IconAcpX, IconAcpY);
				GUI_DrawPolygon(IconAcceptLine6, GUI_COUNTOF(IconAcceptLine6), IconAcpX, IconAcpY);							
				break;
                         default : break ;      
			}
                    GUI_SetColor(GUI_WHITE);
	    	    GUI_DrawPolygon(IconAcceptHand, GUI_COUNTOF(IconAcceptHand), IconAcpX, IconAcpY);    
                    WM_DefaultProc(pMsg) ;
                  
                    break ;   
                     
           }
            default : break ;          
           } 
           break;                    
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       
*/
WM_HWIN CreateWindowIconFirstMenu(void) {
  WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),_cbDialog, WM_HBKWIN,0,0);     

  return hWin;
}

/*************************** End of file ****************************/
