/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Simple_Data_Types.h" 
#include "System_Text_Extern.h"

WM_HWIN CreateFramewinMessageDialog ( const MessageBox_t * Mes ) ; 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0         (GUI_ID_USER + 0x00)
#define ID_BUTTON_0           (GUI_ID_USER + 0x01)
#define ID_TEXT_0             (GUI_ID_USER + 0x02)
#define ID_TEXT_1             (GUI_ID_USER + 0x03)
#define ID_TEXT_2             (GUI_ID_USER + 0x04)

// USER START (Optionally insert additional defines)
// USER END


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
 static MessageBox_t BoxMeseges ;
WM_HWIN ReturnFocus=0  ; 
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, NULL, ID_FRAMEWIN_0, 240,125, 320, 189, 0, 0x64, 0 },
//   { FRAMEWIN_CreateIndirect, NULL, ID_FRAMEWIN_0, 240,0, 320, 189, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, (const char *)&TextString265, ID_BUTTON_0, 110, 122, 90, 32, 0, 0x0, 0 },  //"OK"
  { TEXT_CreateIndirect, NULL, ID_TEXT_0, 13, 14, 271, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, NULL, ID_TEXT_1, 17, 48, 268, 27, 0, 0x0, 0 },
  { TEXT_CreateIndirect, NULL, ID_TEXT_2, 17, 80, 270, 27, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
#define ID_TIMER_TIMER  (GUI_ID_USER + 8)
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
   const WM_PID_STATE_CHANGED_INFO * pInfo;
  
  
  switch (pMsg->MsgId) {
    
     case WM_TIMER: if (WM_GetTimerId(pMsg->Data.v) == ID_TIMER_TIMER)
	            { 
                        GUI_EndDialog(pMsg->hWin,0)           ;   
                    }
		    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    //WM_EnableMemdev(hItem) ;
    FRAMEWIN_SetText(hItem, BoxMeseges.TopString);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem,&GUI_FontVerdana23);
    FRAMEWIN_SetBarColor(hItem,1,GUI_RED)    ;
    //
    // Initialization of 'OK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    WM_SetFocus (hItem) ;  
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_FontVerdana23);
    TEXT_SetText(hItem,BoxMeseges.String1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); 
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem,&GUI_FontVerdana23);
    TEXT_SetText(hItem,BoxMeseges.String2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); 
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem,&GUI_FontVerdana23);
    TEXT_SetText(hItem,BoxMeseges.String3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); 
    
     WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), ID_TIMER_TIMER, 4000, 0);    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
         case WM_NOTIFY_VIS_CHANGED:
                if (WM_IsCompletelyVisible(WM_GetClientWindow(pMsg->hWin))) {

           }
           break ;
    
           
   case WM_PID_STATE_CHANGED:
    pInfo = (const WM_PID_STATE_CHANGED_INFO *)pMsg->Data.p;
    if (pInfo->State) {
      WM_SetFocus(pMsg->hWin);
    }
    break;         
           
  case WM_GET_ACCEPT_FOCUS:
    pMsg->Data.v = 1;
    break ;
    
    
   case WM_KEY: GUI_EndDialog(pMsg->hWin,0)           ;            
                break ;
   case WM_PRE_PAINT:  
             //   if(Cheak_Cover_Windows(WM_GetClientWindow(pMsg.hWin)) && !Cheak_Focus_Windows(WM_GetClientWindow(pMsg.hWin)))
             //   {
              //      WM_SetFocus(WM_GetClientWindow(pMsg.hWin)) ;   
              //  }                
      break ;             
    
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewinMessageDialog( const MessageBox_t * Mes )
{
  WM_HWIN hWin;
  
  BoxMeseges= *Mes   ; 
  hWin = GUI_CreateDialogBox(_aDialogCreate,GUI_COUNTOF(_aDialogCreate),_cbDialog,WM_HBKWIN,0,0);
  return hWin;
}
/** end **/

/*************************** End of file ****************************/
