/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Func_for_GUI_Public.h"
#include "Func_for_Info_KL_AI_Public.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0        (GUI_ID_USER + 0x00)
#define ID_MULTIPAGE_0       (GUI_ID_USER + 0x01)
#define ID_TIMER_TIMER       (GUI_ID_USER + 3)



// USER START (Optionally insert additional defines)
// USER END
extern WM_HWIN CreateFramewinMenuDeviceTableofRespondDevCondAdr03D3KLAI      (void ) ;
extern WM_HWIN CreateFramewinMenuDeviceTableofRespondDevCondAdr03D4KLAI      (void ) ;
extern WM_HWIN CreateFramewinMenuDeviceTableofRespondDevCondAdr03D4_03DCKLAI (void ) ;
extern WM_HWIN CreateFramewinMenuDeviceTableofRespondDevCondAdr03DD_03E1KLAI (void ) ;
extern WM_HWIN CreateFramewinMenuDeviceTableofRespondDevCondAdr03E2_03E5KLAI (void );

WM_HWIN Create_Framewin_Polling_Device_KL_Info_Menu_in_Slave_Single( const AdrDevice_t AdrDevice );


 AdrDevice_t Get_Adr_KL_Info ( void ) ; 

static AdrDevice_t AdrDevice; 
static GuiForMB_t GuiForMB ; 
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect,  "Состояние КЛ АИ ", ID_FRAMEWIN_0, 25, 25, 775, 455, 0, 0x0, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 0, 0, 765, 411, 0, 0x0, 0 },
  //{ LISTVIEW_CreateIndirect,  "Listview", ID_LISTVIEW_0, 3, 28, 750, 385, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId)
  {
    case WM_TIMER: if( WM_GetTimerId(pMsg->Data.v) == ID_TIMER_TIMER)
                  {     
                     if(WM_IsVisible(pMsg->hWin))
                     {
                        switch(MULTIPAGE_GetSelection(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0)))
                        {
                           case 0 : WM_InvalidateWindow(MULTIPAGE_GetWindow(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0),0)); break ; 
                           case 1 : WM_InvalidateWindow(MULTIPAGE_GetWindow(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0),1)); break ;
                           case 2 : WM_InvalidateWindow(MULTIPAGE_GetWindow(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0),2)); break ;
                           case 3 : WM_InvalidateWindow(MULTIPAGE_GetWindow(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0),3)); break ; 
                           case 4 : WM_InvalidateWindow(MULTIPAGE_GetWindow(WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0),3)); break ;
                           default: break ;   
                        }
                     }
                     WM_RestartTimer(pMsg->Data.v,1000);
                  }  
                  break ;
    
    case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin111'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 37);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem,  &GUI_FontVerdana25);
    //
    // Initialization of 'Multipage'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
    MULTIPAGE_SetFont(hItem, &GUI_FontVerdana23);
    MULTIPAGE_SetAlign(hItem, MULTIPAGE_ALIGN_LEFT);
    MULTIPAGE_SetTabHeight(hItem, 30);  
    MULTIPAGE_AddEmptyPage(hItem, CreateFramewinMenuDeviceTableofRespondDevCondAdr03D3KLAI () , "Состояние");
    MULTIPAGE_AddEmptyPage(hItem, CreateFramewinMenuDeviceTableofRespondDevCondAdr03D4KLAI () , "Ошибки");
    MULTIPAGE_AddEmptyPage(hItem, CreateFramewinMenuDeviceTableofRespondDevCondAdr03D4_03DCKLAI () , "Ошибки ЛС");
    MULTIPAGE_AddEmptyPage(hItem, CreateFramewinMenuDeviceTableofRespondDevCondAdr03DD_03E1KLAI () , "Ошибки MODBUS");
    MULTIPAGE_AddEmptyPage(hItem, CreateFramewinMenuDeviceTableofRespondDevCondAdr03E2_03E5KLAI () , "V,A в ЛС");
    
    
    MULTIPAGE_SelectPage(hItem,0);
    WM_SetFocus(hItem) ;
    
    WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), ID_TIMER_TIMER,1000,0); 
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
    case WM_KEY:    
                 switch (pMsg->Data.v)
                    {        
                         case GUI_KEY_ENTER_HAND :
                                                   break ;                                                 
                        case GUI_KEY_LEFT_HAND:  {                                                    
                                                      uint8_t pp=MULTIPAGE_GetSelection(WM_GetDialogItem(pMsg->hWin,ID_MULTIPAGE_0)) ;
                                                      if(pp)
                                                      {
                                                        pp-- ;
                                                      }
                                                      else
                                                      {
                                                        pp=4 ;
                                                      }
                                                      MULTIPAGE_SelectPage ( WM_GetDialogItem ( pMsg->hWin , ID_MULTIPAGE_0 ) , pp ) ;                                                   
                                                    }                     
                                                    break ;                                                     
                           case GUI_KEY_RIGHT_HAND: {    
                                                      uint8_t pp = MULTIPAGE_GetSelection ( WM_GetDialogItem ( pMsg->hWin , ID_MULTIPAGE_0 ) ) ;
                                                      if(pp<4)
                                                      {
                                                        pp++ ;
                                                      }
                                                      else
                                                      {
                                                        pp=0 ;
                                                      }                                                       
                                                      MULTIPAGE_SelectPage(WM_GetDialogItem(pMsg->hWin,ID_MULTIPAGE_0),pp)   ;                                                  
                                                    }                             
                                                     break ;                                             
                         case GUI_KEY_UP_HAND    :                                                                                    
                                                     break ;                                                                                        
                         case GUI_KEY_DOWN_HAND: 
                                                     break ;                                                                              
                         case GUI_KEY_ESCAPE_HAND :  GUI_EndDialog(pMsg->hWin,1)    ;
                                                     Set_Request_KLAI (AdrDevice.KL ,False ) ;  
                                                     break ;                                            
                      default: break ;                        
                    }
                 break ;   
   case WM_POST_PAINT:  
                       if ( !Cheak_Focus_Windows ( WM_GetClientWindow ( pMsg -> hWin ) ) )
                       {
                         if ( Cheak_Cover_Windows_2 ( WM_GetClientWindow ( pMsg -> hWin ) ) )
                         {
                            WM_SetFocus ( pMsg -> hWin ) ;   
                         }
                       }
                       break ;  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
       case WM_NOTIFICATION_GOT_FOCUS :
                   // Fill_Table ( pMsg->hWin ) ;
          break ;    
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;  
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       
*/
WM_HWIN Create_Framewin_Polling_Device_KL_Info_Menu_in_Slave_Single( const AdrDevice_t AdrDeviceIn )
{
  WM_HWIN hWin;

  if ( Check_GUI_RAM () )
  {
    Set_Request_KLAI (AdrDevice.KL ,True ) ;
    AdrDevice=  AdrDeviceIn ;
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  }
  return hWin;
}

  /****************************************************************************
  * Имя функции   : Get_Adr_KL_Info
  * Описание      : вернуть выбранный адрес
  * 
  *
  * Параметры     : нет
  * Возврат       : AdrDevice_t
  ****************************************************************************/

AdrDevice_t Get_Adr_KL_Info ( void )
{ 
  return AdrDevice ; 
}
   /** end **/
/*************************** End of file ****************************/
